### ISSUE TITLE
ThinQ1 Status updates retrieving stale data for washer/dryer.

### ISSUE THREAD

**Issue by ekobres** [nVuln/homebridge-lg-thinq#100]
**Describe The Bug:**

The plugin will poll status of washer until it completes one cycle and goes into power off state. After this, all subsequent updates show no change, even though washer and LG app continue to correctly operate and update status. It appears from debug log like the api is being called but never returns anything new.

As far as I know, previous versions to 1.2.10 also have this issue. I have never gotten this plugin to work for more than a single load of laundry without having to restart the plugin.
**To Reproduce:**

Enable for ThinQ1 washer and complete 2 cycles. After the first cycle, polled status will never change again until child bridge is restarted.
**Expected behavior:**

Continued polling…
**Logs:**
(Note: this pair of messages repeats as far back as I can see in the log and - as here - 47 times during the load that is running - and continues after. the LG app shows the correct status and time remaining the whole time.)
```
[05/11/2021, 12:37:46] [homebridge-lg-thinq] [request] post https://aic.lgthinq.com:46030/api/rti/rtiResult
[05/11/2021, 12:37:46] [homebridge-lg-thinq] [Washer] Received snapshot:  {"washerDryer":{"state":"POWEROFF","preState":"POWEROFF","remoteStart":"REMOTE_START_OFF","initialBit":"INITIAL_BIT_OFF","childLock":"CHILDLOCK_OFF","TCLCount":0,"reserveTimeHour":0,"reserveTimeMinute":0,"remainTimeHour":0,"remainTimeMinute":0,"initialTimeHour":0,"initialTimeMinute":0,"soilWash":"NO_SOILWASH"},"raw":{"State":null,"Remain_Time_H":null,"Remain_Time_M":null,"Initial_Time_H":null,"Initial_Time_M":null,"APCourse":null,"Error":null,"Soil":null,"SpinSpeed":null,"WaterTemp":null,"RinseOption":null,"DryLevel":null,"Reserve_Time_H":null,"Reserve_Time_M":null,"Option1":null,"Option2":null,"Option3":null,"PreState":null,"SmartCourse":null,"TCLCount":null,"OPCourse":null,"LoadLevel":null}}
```

**Plugin Config:**

```
        {
            "country": "US",
            "language": "en-US",
            "auth_mode": "token",
            "refresh_token": "*****",
            "username": "",
            "password": "",
            "devices": [
                {
                    "id": "*****",
                    "name": "Dryer",
                    "type": "DRYER",
                    "washer_door_lock": true
                },
                {
                    "id": "*****",
                    "name": "Washer",
                    "type": "WASHER",
                    "washer_trigger": true
                }
            ],
            "thinq1": true,
            "refresh_interval": 60,
            "platform": "LGThinQ",
            "_bridge": {
                "username": "0E:14:13:4A:4D:75",
                "port": 36445
            }
```

**Screenshots:**

**Environment:**
Raspbian RPi 3b - homebridge latest.
* **Plugin Version**: 1.2.10 (test)
* **Homebridge Version**:  1.3.5 
* **Node.js Version**: 14.17.4 
* **NPM Version**: 7.20.3
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
please install `v1.2.11-test.1` and try.
sorry I don't have thinq1 device, so I can't test it, need your help

**Comment by malwcal** [comment]
BTW, I have also had issues with my thinq1 washer status not being updated correctly.  I assume its the same issue.  I am also trying these test versions to see if they help.

**Comment by ekobres** [comment]
The test version 1.2.11.test.1 does not improve the situation for me. In this case the first load was never detected either. All messages state pwroff. First app was run hours after restrting bridge. LG app still working properly for status and alerts.

**Comment by RuiMSM** [comment]
I am so sorry for the most stupid question. Could you please tell me how does one retrieve the device id from the washer? I tried to look for it in the native app but it doesn't seem to come from there. Can you please help with this?

**Comment by nVuln** [comment]
> I am so sorry for the most stupid question. Could you please tell me how does one retrieve the device id from the washer? I tried to look for it in the native app but it doesn't seem to come from there. Can you please help with this?

Please turn on homebridge debug mode, you can see device id and other data in debug logging

**Comment by malwcal** [comment]
I will raise a separate ticket for my own issues.

**Comment by nVuln** [comment]
@ekobres please try `v1.2.11-test.2`

**Comment by ekobres** [comment]
> @ekobres please try `v1.2.11-test.2`

This version seems to fail immediately after the “Start polling device data…” message. I never see another entry after this. Previously I would see messages every 60 seconds. No status updates or updated info is making it into the accessory.

**Comment by nVuln** [comment]
> > @ekobres please try `v1.2.11-test.2`
> 
> This version seems to fail immediately after the “Start polling device data…” message. I never see another entry after this. Previously I would see messages every 60 seconds. No status updates or updated info is making it into the accessory.

even washer running ?
in this version, if device is not connect or data unable to get, I don't perform update so no logging is wrote in debug, maybe your device is not running, try start it and see if status updated without bridge restart needed

**Comment by ekobres** [comment]
> even washer running ?
> in this version, if device is not connect or data unable to get, I don't perform update so no logging is wrote in debug, maybe your device is not running, try start it and see if status updated without bridge restart needed 

Okay, knowing this, I have now seen it work correctly for at least 4 wash cycles in a row. So it looks like `v1.2.11-test.2` does resolve the plugin completely failing to update status for my particular ThinQ1 accessories.

Thank you!
