### ISSUE TITLE
thinq1 occupancy sensor unreliable

### ISSUE THREAD

**Issue by malwcal** [nVuln/homebridge-lg-thinq#101]
**Describe The Bug:**
While my thinq1 washer is running I get random notifications that the occupancy sensor has been activated.

**To Reproduce:**
Run a washing cycle, with notifications turned on.  

**Expected behavior:**
My understanding is that the occupancy sensor should only activate when the washing cycle is finished.
**Logs:**

I can provide these if needed.

**Plugin Config:**

Again can be provided if needed

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
please try install `v1.2.11-test.2`, 
if this issue still not fixed, turn on homebridge debug mode, wait homebridge running a few minute, then upload debug log
you can found something like this `[LGThinQ] [device name] Received snapshot:` in debug logging

**Comment by malwcal** [comment]
HI,

This seems fixed with this version.

I will keep an eye this over the next few days.
