### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by beliy82** [nVuln/homebridge-lg-thinq#105]
**Describe The Bug:**

I got a server error in logs, before the update its all worked fine (i got fridge)
**To Reproduce:**

**Expected behavior:**

**Logs:**
[23/11/2021, 14:54:05] [LGThinQ] LG ThinQ internal server error, try again later.
[23/11/2021, 14:54:05] [LGThinQ] 
```
Show the Homebridge logs here (make sure homebridge DEBUG mode is turned `on`), remove any sensitive information.
```

**Plugin Config:**

```
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by nVuln** [comment]
try restart bridge 1-2 times and see if it's worked again, this error because trouble on connection to LG server
you should turn on homebridge debug mode for more detail

**Comment by beliy82** [comment]
> try restart bridge 1-2 times and see if it's worked again, this error because trouble on connection to LG server you should turn on homebridge debug mode for more detail

restarted it several times, and in thinq app all works

**Comment by nVuln** [comment]
> > try restart bridge 1-2 times and see if it's worked again, this error because trouble on connection to LG server you should turn on homebridge debug mode for more detail
> 
> restarted it several times, and in thinq app all works

please turn on homebridge debug mode, you will see more debug logging

**Comment by beliy82** [comment]
[LGThinQ] NotConnectedError: 
    at /usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/request.ts:38:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Auth.getJSessionId (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/Auth.ts:139:30)
    at API.refreshNewToken (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:5)
    at API.ready (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:237:7)
    at ThinQ.isReady (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:292:5)

**Comment by nVuln** [comment]
> [LGThinQ] NotConnectedError: at /usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/request.ts:38:11 at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) at Auth.getJSessionId (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/Auth.ts:139:30) at API.refreshNewToken (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:254:5) at API.ready (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/API.ts:237:7) at ThinQ.isReady (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:292:5)

I'm not sure reason for this error, something I got error like this because my network got trouble, but when I restarted it after 5-10 minute, it's worked again
at the time you reported it, I tried also and see connection to LG server is slower than normal, maybe that is problem

**Comment by beliy82** [comment]
i used to connect with apple ID and used token,
now i open a new account with LG account and its the same :(

what else can i do?

**Comment by beliy82** [comment]
now reinstall the plugin and its stuck on this screen

![image](https://user-images.githubusercontent.com/71979517/143783969-0a292469-80f6-4343-ad5c-af19f97b4b15.png)

the wheel is spinning non stop

**Comment by nVuln** [comment]
please re-check network from homebridge device, look like your network (from device running homebridge) is too slow while connecting to LG server

**Comment by beliy82** [comment]
thanks!
