### ISSUE TITLE
Homebridge down after update

### ISSUE THREAD

**Issue by adamrzanek** [nVuln/homebridge-lg-thinq#107]
**Describe The Bug:**
Homebridge down after latest update

**To Reproduce:**
Homebridge stuck on starting page 

**Expected behavior:**
Should start homebridge

**Comment by nVuln** [comment]
if you got trouble on homebridge, please report at [Homebridge Repo](https://github.com/homebridge/homebridge)

**Comment by adamrzanek** [comment]
Yes, but it happened after updating your plugin not homebridge itself

**Comment by nVuln** [comment]
Please give more detail, plugin version, homebridge version, device running homebridge, os ... please check homebridge log also
It don't happened on my device, I can't detect problem without any information
