### ISSUE TITLE
Settings panel in homebridge-config-ui-x permanently stuck on spinning gear

### ISSUE THREAD

**Issue by larsjuhw** [nVuln/homebridge-lg-thinq#109]
**Describe The Bug:**
The settings menu of this plugin in homebridge-config-ui-x is stuck on the spinning gear animation forever, [as shown here.](https://user-images.githubusercontent.com/39745476/144475697-9afc4c2c-07d2-4e12-9691-dd994f7133a8.png)
I assumed that this was caused by [this fix](https://github.com/oznu/homebridge-config-ui-x/pull/1198) that was added to the latest version of homebridge-config-ui-x (4.41.3), but I can confirm this is reproducible on v4.41.2 and some older version (forgot which v). From the logs, I assume that this bug is caused by[ the removal of get-login-url](https://github.com/nVuln/homebridge-lg-thinq/commit/974b70c45cc5326cde5f610cb46c4b9ae9c3f664) from server.js

**To Reproduce:**
* Install homebridge-lg-thinq@1.2.11
* Remove the homebridge-lg-thinq entry from your config file (not sure if necessary)
* Go to the Homebridge UI -> Plugins -> Homebridge LG ThinQ [Settings] button

**Expected behavior:**
* The settings panel loads as intended.

**Logs:**

Currently no debug logs, but these are the logs for both version when after closing the plugin settings panel:
v1.2.10
```
[Homebridge UI] [homebridge-lg-thinq] Incoming Request: /get-login-url
[Homebridge UI] [homebridge-lg-thinq] Terminating child process...
[Homebridge UI] [homebridge-lg-thinq] Child process ended
```

v1.2.11
```
[Homebridge UI] [homebridge-lg-thinq] Terminating child process...
[Homebridge UI] [homebridge-lg-thinq] Child process ended
```

Note that the latest version does not have the "Incoming Request" line.

**Plugin Config:**
Config contains no entry for thus plugin yet.

**Screenshots:**
![image](https://user-images.githubusercontent.com/39745476/144475697-9afc4c2c-07d2-4e12-9691-dd994f7133a8.png)

**Environment:**

* **Plugin Version**: 1.2.11
* **Homebridge Version**: 1.3.0
* **Node.js Version**: 14.18.1
* **NPM Version**: 6.14.15
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
I have published new version to fix this issue, please update

**Comment by Rubske70** [comment]
I had the same issue and the latest update fixed the issue.

Thanks!

Regards

Rob
