### ISSUE TITLE
AC RAC_056905_WW API_1

### ISSUE THREAD

**Issue by WojtekWro** [nVuln/homebridge-lg-thinq#111]
**Describe The Bug:**
The plugin doesn't work correctly with my AC. AC is visible in HomeKit. It reads correctly current status from the device, but it is not able to control the device from HomeKit/Homebridge. 

**Logs:**

 [12/6/2021, 2:15:47 PM] [LGThinQ] request error:  Error: Request failed with status code 400
    at createError (/homebridge/node_modules/homebridge-lg-thinq/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-lg-thinq/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-lg-thinq/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://eic-service.lgthinq.com:46030/v1/service/devices/d27b65d0-7149-11d3-80ad-2c2bf9f16454/control-sync',
    method: 'post',
    data: '{"ctrlKey":"basicCtrl","command":"Operation","dataKey":"airState.operation","dataValue":0}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'x-api-key': 'VGhpblEyLjAgU0VSVklDRQ==',
      'x-thinq-app-ver': '3.6.1200',
      'x-thinq-app-type': 'NUTS',
      'x-thinq-app-level': 'PRD',
      'x-thinq-app-os': 'ANDROID',
      'x-thinq-app-logintype': 'LGE',
      'x-service-code': 'SVC202',
      'x-country-code': 'PL',
      'x-language-code': 'pl-PL',
      'x-service-phase': 'OP',
      'x-origin': 'app-native',
      'x-model-name': 'samsung/SM-G930L',
      'x-os-version': 'AOS/7.1.2',
      'x-app-version': 'LG ThinQ/3.6.12110',
      'x-message-id': '5zQNflVyGPd0ibie3cPlsb',
      'user-agent': 'okhttp/3.14.9',
      'x-emp-token': '698181bc4f701cc27af9f8xxxxxxx',
      'x-user-no': 'PL1906221xxxxxx',
      'x-client-id': '35384aac9b5c2dee87ca4005ac80965xxxxxxxx',
      'Content-Length': 90
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 60000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    'axios-retry': { retryCount: 0, lastRequestTime: 1638796546804 }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'eic-service.lgthinq.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'eic-service.lgthinq.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 60000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.2.12
* **Homebridge Version**: v1.3.8
* **Node.js Version**: v16.13.0
* **NPM Version**: v8.1.0
* **Operating System**: Docker/ Ubuntu Bionic Beaver (18.04.6 LTS)

**Comment by nVuln** [comment]
can you help me install test version `1.2.13-test.1` and see if it's worked?

**Comment by WojtekWro** [comment]
First of all I want thank you. I’m impressed how fast you are. 
The beta works fine. Now I have two way communication.
