### ISSUE TITLE
Request to fix missing notifications on LG Dryer

### ISSUE THREAD

**Issue by frankebobdk** [nVuln/homebridge-lg-thinq#114]
**Which device do you want to add? Please describe:**

I would like the LG Dryer FDRC308N2W9 to be added. 

**Describe the solution you'd like:**

The device is showing up in Homebridge as intended, but the "Enable Door Lock Status" is not working. It is not showing up in Homekit. 

I have also tried to use the "Enable Program Finished Trigger". But this does not work either. No notifications is send when the job is done. But at least the "trigger" is showing up in homekit. 

**Device Data:**

[LGThinQ] [DRYER] Setting up device!
[LGThinQ] Restoring existing accessory: 9300d8a4-fd35-1cb8-84f7-f8b95abc4900: DRYER (DRYER RC90V9_WW)

**Comment by nVuln** [comment]
please turn all homebridge debug mode and upload all debug logging
<img width="453" alt="homebridge debug mode" src="https://user-images.githubusercontent.com/54855446/145796223-a958a0b0-080d-4e37-8ddb-22f96cd905ed.png">

door lock status support only in thinq2, maybe your dryer is using thinq1

**Comment by frankebobdk** [comment]
The Dryer should be a ThingQ2 - as I can control it in the app and also through my tv ;-)

Should I run a program on the dryer in order for you to get the necessary data?

**Comment by nVuln** [comment]
> The Dryer should be a ThingQ2 - as I can control it in the app and also through my tv ;-)
> 
> Should I run a program on the dryer in order for you to get the necessary data?

first, I need device data wrote on debug logging to figure out door lock problem
if you have time to run dryer and get more data, it's very awesome

**Comment by frankebobdk** [comment]
Here is the first debug log that I got.

I'm currently doing a program on the dryer, and will upload that data once is done. 

[homebridge.log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7703158/homebridge.log.txt)

**Comment by nVuln** [comment]
> Here is the first debug log that I got.
> 
> I'm currently doing a program on the dryer, and will upload that data once is done.
> 
> [homebridge.log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7703158/homebridge.log.txt)

is door lock tile showing up on homebridge accessories ?
I just checked and saw you have 2 device, right ?

device name "TØRRETUMBLER" is not support doorLock status (I can't see this variable in device snapshot data, only childLock), and this is dryer
device name "VASKEMASKINE" is support door lock status

**Comment by frankebobdk** [comment]
Correct, I got 2 devices. 

Tørretumbler = Dryer.
Vaskemaskine = Washer. 

The Door lock status is working perfectly on the washer, and the same goes for the Occupancy Sensor.

But the Occupancy Sensor doesn't work for the Dryer for some reason. 
If the doorlock status isn't supportet for the dryer, well that explains why I can't get it to work :)

**Comment by frankebobdk** [comment]
[homebridge.2.log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7703750/homebridge.2.log.txt)

Here is the logs from when the dryer finished the program. Still no Occupancy Sensor notifications

**Comment by nVuln** [comment]
> [homebridge.2.log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7703750/homebridge.2.log.txt)
> 
> Here is the logs from when the dryer finished the program. Still no Occupancy Sensor notifications

please install test version `v1.2.14-test.4` and see if it's worked in next time you dry

**Comment by frankebobdk** [comment]
It' works! :) thanks for your support.
