### ISSUE TITLE
Interface with NodeRed

### ISSUE THREAD

**Issue by cinadr** [nVuln/homebridge-lg-thinq#137]
**I need some help with A/C current values accepted**

I'm trying to connect OpenHAB to HomeBridge and I found a way to do it through Node-RED. It offers two plugins that is working with both smarthome software. I managed so far to turn AC unit on/off from OpenHAB. Also turning on and off from HomeBridge is gets back to OpenHAB switch as well.

My question is about the JSON structure that Node-RED sends and gets from HomeBridge. Which is the following:
```json
{
 "Active":1,
 "CurrentHeater-CoolerState":2,
 "TargetHeater-CoolerState":1,
 "CurrentTemperature":23,
 "CoolingThresholdTemperature":25,
 "HeatingThresholdTemperature":25,
 "RotationSpeed":1,
 "SwingMode":0
}
```
My main question is about the numbers. What do they mean? I cannot find any clear description of the. (Temperature values are self explanatory, of course.)
How to set AC unit to Heat/Cool/Auto. I noticed that the TargetHeater-CoolerState is only changes to 1 and 2. If I press Auto inside Homebridge I don't get a change inside JSON. Changing Target value alone does not turn on AC unit. Do I need to send Active as well?
What is RotationSpeed means. I found 2,3,4,5 in source code but value 1 is missing.
What is SwingMode value means (Both, Vertical,Horizonal,None) Which one is which?
Can you point me to some API source to figure this out?

<details><summary>**Config:**</summary>
<textarea>
{
    "bridge": {
        "name": "Homebridge FFFF",
        "username": "xxxxxxxxxxxxxxxx",
        "port": 51806,
        "pin": "xxxxxxxxxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        },
        {
            "country": "HU",
            "language": "hu-HU",
            "auth_mode": "token",
            "refresh_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "username": "xxxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "devices": [
                {
                    "id": "009fa4cb-1a7f-1102-845c-24e8536d9304",
                    "name": "Hálószoba",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": false
                },
                {
                    "id": "058cfc00-1db0-11b8-a576-1c3929041324",
                    "name": "Hűtőgép",
                    "type": "REFRIGERATOR",
                    "ref_express_freezer": false,
                    "ref_express_fridge": true
                },
                {
                    "id": "2963124d-1028-1d98-9690-24e8536d5d4c",
                    "name": "Játszószoba",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": false
                },
                {
                    "id": "45756ba2-d571-1aa8-8466-24e8536cd969",
                    "name": "Gyerekszoba",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": false
                },
                {
                    "id": "d27bb3f0-7149-11d3-80af-a06faae627a8",
                    "name": "Garázs",
                    "type": "AC",
                    "ac_air_quality": false,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": false
                },
                {
                    "id": "d27c0210-7149-11d3-80b1-a06faae546f9",
                    "name": "Nappali",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": false
                }
            ],
            "refresh_interval": 60,
            "thinq1": true,
            "platform": "LGThinQ"
        }
    ]
}
</textarea>
</details>

**Environment:**

* **Plugin Version**: v1.2.14
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**: 8.3.1
* **Operating System**: Docker

**Comment by nVuln** [comment]
you can see it here: https://developers.homebridge.io/#/service/HeaterCooler
`RotationSpeed`: 2,3,4,5 is just value mapped from thinq api (don't care about it), in homebridge it's 1,2,3,4 (`0` mean AC off)
`SwingMode` only accept value `0` or `1`, mean `enabled` or `disabled`
Auto button in homebridge is Switch service: https://developers.homebridge.io/#/service/Switch (not listed on provided json)

**Comment by cinadr** [comment]
Thank you for your answer! It helps me a lot.
