### ISSUE TITLE
No device ID + 0110 - 약관동의 미동의 상태입니다.

### ISSUE THREAD

**Issue by alexpgates** [nVuln/homebridge-lg-thinq#138]
**Describe Your Problem:**
I'm having trouble with configuring the plugin to work with my LG washer. 
I'm able to obtain a refresh token. However, I'm not sure where to locate my device ID. Is it required? 

If simply leaving the device ID empty enables all devices in my account, I'm still having an issue with the API:

**Logs:**

```
[26/02/2022, 21:58:07] [LGThinQ] ThinQ API is not ready. please check configuration and try again.
[26/02/2022, 21:58:07] [LGThinQ] 0110 - 약관동의 미동의 상태입니다.
```

Note - that error in the logs translates to:" I do not agree to the terms and conditions"

**Plugin Config:**

```json
{
    "country": "US",
    "language": "en-US",
    "auth_mode": "token",
    "refresh_token": "*******",
    "username": "******",
    "password": "********",
    "platform": "LGThinQ",
    "devices": [],
    "thinq1": false,
    "refresh_interval": 60
}
```

**Environment:**

* **Plugin Version**:
* v1.2.14
* **Homebridge Version**: 
* v1.4.0
* **Node.js Version**: 
* v16.14.0
* **NPM Version**: 
* v8.3.1
* **Operating System**: 
* Raspbian

**Comment by nVuln** [comment]
please try login to LG ThinQ mobile app (signed out and re-signin)

**Comment by alexpgates** [comment]
Thank you! I signed out and back in several times and am still receiving the same error in my console.

**Comment by nVuln** [comment]
> Thank you! I signed out and back in several times and am still receiving the same error in my console.

that error said you not yet agree their terms & conditions, it should appear when you logged into mobile app
I don't know why you don't see it 😶‍🌫️

**Comment by bottlebug** [comment]
I'm getting the same issues and I've accepted all terms and conditions.

**Comment by vincentchew91** [comment]
Got the same issue,. Was working ok for the past 3 months until today. I have tried signing out and login the LG ThinQ app, did not receive pop out or notification about terms & conditions.

**Comment by nVuln** [comment]
> Creating new account and accepting the term and condition prompt again seems to work. I suspect there is a new terms and condition that are not push to existing user (yet?).

I'm not sure about this, it's not happened to me (country code VN), I'm still investigate this problem

**Comment by davida61** [comment]
It looks like there are new terms and conditions dated March 31 2022, whilst there is a notification about them coming in "Notices & Updates" there does not appear to be a way to accept them yet. It says you will be invited to accept them but this has not occurred for me and others it seems.

**Comment by nVuln** [comment]
@bottlebug @alexpgates @davida61  are you resolved this issue ? if not, please turn on homebridge debug mode, then restart homebridge and show some debug logging, let see

**Comment by davida61** [comment]
A workaround

- Create a new account
- Accept the terms & privacy on the new account
- From the original account invite the new account as a "member" to the original account 
- from the new account accept the invite
- use the new account credentials in Homebridge 

All should now be working

The new terms are in English and may not exist in other languages yet so some countries may be fine.

It would appear to be an LG problem as there is no way for an existing user to accept the new terms from 31 March 2022.

**Comment by nVuln** [comment]
@davida61 did you used thinq1 device? look like this error responsed from thinq1 api endpoint

**Comment by davida61** [comment]
@nVuln 

I do not think so, config is 

{
    "auth_mode": "account",
    "username": "xxxxxxx",
    "password": "xxxxxxx",
    "country": "AU",
    "language": "en-AU",
    "thinq1": false,
    "washer_trigger": true,
    "platform": "LGThinQ",
    "devices": [
        {
            "id": "xxxxxx-1c3b-132b-af57-xxxx",
            "name": "Refrigerator",
            "ref_express_freezer": true
        },
        {
            "id": "xxxxxx-e800-160b-88e4-xxxxxx",
            "name": "Dishwasher"
        }
    ]
}

Only difference between working and non-working config is the username, the new account works, old one does not :-(
