### ISSUE TITLE
Unable to set device room

### ISSUE THREAD

**Issue by asolochek** [nVuln/homebridge-lg-thinq#139]
Hi, 

I ended up here after homebridge-lg-thinq-ac failed to work with 1 of my airconditioners (odd, since the LW1019IVSM AC apparently uses thinq1, while the same generation unit, but larger capacity, the LW1517IVSM, uses thinq2).

All 3 airconditioners I have are detected and show up in homekit, however they all show up listed in the room where my homebridge is. Unlike all the accessories provided by other plugins, there is no "room" setting for these air conditioners within homekit to move them to the correct rooms. 

It feels like a bug that there isn't a way to specify which room the thinq devices are in.

**Comment by nVuln** [comment]
can you capture some screenshot in home app about this issue ?

**Comment by asolochek** [comment]
Sure. Also, while testing this, I noticed that there was quite a delay between turning an air conditioner on in homekit and the air conditioner actually turning on. Maybe a 30 second delay. Is this plugin doing some 30 second update thing?

"Office Airconditioner" is connected using this plugin. 

![IMG_0742](https://user-images.githubusercontent.com/1464528/156144761-03a316aa-7ed7-413e-afac-40a0cabd9f4b.jpeg)

The "Livingroom Airconditioner" picture is using the lq-thinq-ac plugin. 
![IMG_0739](https://user-images.githubusercontent.com/1464528/156144860-e1250e41-17b0-413e-8546-1582d59b0bc4.jpeg)

**Comment by asolochek** [comment]
damn, sorry for the size of those images.

**Comment by nVuln** [comment]
> Sure. Also, while testing this, I noticed that there was quite a delay between turning an air conditioner on in homekit and the air conditioner actually turning on. Maybe a 30 second delay. Is this plugin doing some 30 second update thing?

thing1 device is update every 60 second as default, you can setting `refresh_interval` in plugin config to change this value, but I think you shouldn't decrease it too low, 30 - 60 second is best practice or you can received a warning from LG about unusual request
thinq2 update in realtime via mqtt protocol (thinq1 do not support this)



> "Office Airconditioner" is connected using this plugin.

look like this AC tile is single tile in group of AC services (fan, AC, light ...), you need click "Show as Separate Tile" before you can change room of this single tile
or you can change room in root accessory

**Comment by asolochek** [comment]
The "Office Airconditioner" was the only tile added for that device, so I assumed it was the root, however clicking "show as seperate tiles" did make the room assignment setting appear (even though it didn't show any additional tiles) so thanks!

So the other plugin that only supports thinq2 does work with my office and livingroom air conditioners, just not the bedroom. So shouldn't the two thinq2 devices have ~instant control? Because they don't. Does checking the "enable thinq1 support" box make all devices use thinq1?

**Comment by asolochek** [comment]
I just tried unchecking the thinq1 support option and that did result in the bedroom AC being removed as a device, but the other two ACs are still slow to respond. Is there some configuration I could add to make this plugin only expose the thinq1 bedroom AC?

**Comment by nVuln** [comment]
> I just tried unchecking the thinq1 support option and that did result in the bedroom AC being removed as a device, but the other two ACs are still slow to respond. Is there some configuration I could add to make this plugin only expose the thinq1 bedroom AC?

if you using homebridge-ui, you can go to plugin setting to remove unwanted device or following this https://github.com/nVuln/homebridge-lg-thinq/wiki/Device-Configuration to enable thinq1 device only

**Comment by nVuln** [comment]
> So the other plugin that only supports thinq2 does work with my office and livingroom air conditioners, just not the bedroom. So shouldn't the two thinq2 devices have ~instant control? Because they don't. Does checking the "enable thinq1 support" box make all devices use thinq1?

I'm not sure if the other plugin used mqtt protocol like this plugin
if you using this plugin to control thinq2 device, and it's still slow response, maybe the problem is your slow network, please turn on homebridge debug mode, you can see real-time device data in-out
