### ISSUE TITLE
Washer door 

### ISSUE THREAD

**Issue by adamrzanek** [nVuln/homebridge-lg-thinq#14]
I’m writing this because I wanted to thank you for doing this plugin! 
I have to ask two questions:
1. Is it possible to add washer door sensor? 
2. is it possible to add power consumption in eve app?
Thanks again

**Comment by nVuln** [comment]
1. LG washer don't have contact sensor for washer door (only door locked status)
2. also they don't have internal power consumption sensor, you may use external device to track it

**Comment by adamrzanek** [comment]
Thanks. So maybe you can expose this Door Lock machanism?

**Comment by nVuln** [comment]
1. LG washer don't have contact sensor for washer door (only door locked status)
2. also they don't have internal power consumption sensor, you may use external device to track it

**Comment by nVuln** [comment]
> Thanks. So maybe you can expose this Door Lock machanism?
> […](#)
> On 2 Jun 2021, at 10:46, nVuln ***@***.***> wrote: ﻿ LG washer don't have contact sensor for washer door (only door locked status) also they don't have internal power consumption sensor, you may use external device to track it — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, but do you think it's useful ? I think it's not 😨 (I already added it before and removed it for now)
door always locked when running and unlock when it's completed 😵‍💫

**Comment by adamrzanek** [comment]
Oh I see usage for this. I can create fake switch to check if the laundry was removed after the washer is done. Or we can make native notification that door is unlocked so it’s done working. :)

**Comment by adamrzanek** [comment]
Sorry the first part is not useful without door sensor. But notification can be done

**Comment by adamrzanek** [comment]
If you find it useful - i’ve made siri shortcut to check your washer status with siri 🤗 

![8E9A61D6-326E-4831-8731-FB0BD466E9B3](https://user-images.githubusercontent.com/65444919/120460190-2d28e700-c399-11eb-99ff-1ad4905c56a9.jpeg)

**Comment by adamrzanek** [comment]
Sorry to bother you but is it possible to implement the door lock anyway as an option? It would be really useful for me for notifications when I’m not at home :)

**Comment by nVuln** [comment]
> Sorry to bother you but is it possible to implement the door lock anyway as an option? It would be really useful for me for notifications when I’m not at home :)

sure, I'll turn it on in next release

**Comment by adamrzanek** [comment]
Thanks !

**Comment by adamrzanek** [comment]
Thanks for implementing this. I hava small problem - The washer is showing „unlocking” status when it is running the program. Because of this i don’t have notification when it’s unlocked. Thanks

![CF322250-C7DC-4F6E-A63A-0818DCDEAEB7](https://user-images.githubusercontent.com/65444919/122682071-b5134b80-d1f7-11eb-9483-bf7028807fa4.png)
