### ISSUE TITLE
 “Not responding”  error after I tried to turn off/on the dishwasher

### ISSUE THREAD

**Issue by carlosgamezvillegas** [nVuln/homebridge-lg-thinq#142]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here (make sure homebridge DEBUG mode is turned `on`), remove any sensitive information.
```

**Plugin Config:**

```
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: <1.4.0-->
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by nVuln** [comment]
sorry, currently dishwasher is monitor only, cannot control from homebridge
