### ISSUE TITLE
is it possible to control the washer using this home bridge app?

### ISSUE THREAD

**Issue by PeterWan816** [nVuln/homebridge-lg-thinq#148]
**Which device do you want to add? Please describe:**

**Describe the solution you'd like:**

just a feature request. it would be really nice to allow remote start for the tub cleaning process with the help of the plugin/homebridge, since it doesn't seem to be supported by the official app. 
**Device Data:**

**Comment by nVuln** [comment]
is your washer keep REMOTE START always ON even washer restarted? (my washer doesn't, remote start always off and I need manual turn it ON when I start washer)
