### ISSUE TITLE
Adding LG HOM-BOT Robot Vacuum Cleaner

### ISSUE THREAD

**Issue by Slavitacus** [nVuln/homebridge-lg-thinq#15]
Hello,

Could it be possible to implement the LG HOM-BOT Robot Vacuum Cleaner
 to the plugin?

Thank you very much

**Comment by nVuln** [comment]
please install plugin, turn on homebridge debug mode, you can see device data of your robot vacuum in debug logging
please upload it here, I'll do my best to implement it

**Comment by Slavitacus** [comment]
Hello,
Is this good?

`[6/11/2021, 3:29:54 PM] [LGThinQ] Found device:  4AA0A580-B313-4E89-BF42-30a9de7bbdaa: Iron Man (ROBOT_KING HITWIFI)`
`[6/11/2021, 3:29:54 PM] [LGThinQ] data:  {"deviceId":"4AA0A580-B313-4E89-BF42-30a9de7bbdaa","deviceType":501,"modelName":"HITWIFI","subModelNm":null,"sensorType":null,"alias":"Iron Man","deviceCode":"LI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Chalet Taroko","timezoneCode":"Europe/Paris","timezoneCodeAlias":"Europe/Paris","sdsGuide":"{\"deviceCode\":\"LI01\"}","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"623","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20190821171432000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.3","modelJsonUri":"https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=HITWIFI&countryCode=FR&contentsId=JS2016053100000782&authKey=thinq","appModuleVer":"12.22","appModuleUri":"https://objectcontent.lgthinq.com/331b96aa-ef81-42f8-a147-13d17f04f4ea?hdnts=exp=1685061033~hmac=700f1b1a155ec7f37f34d38dbcee46f0af5fcffe249f3e5f5f00e07903550fc0","appRestartYn":"Y","appModuleSize":"14365987","langPackProductTypeVer":"59.7","langPackProductTypeUri":"https://objectcontent.lgthinq.com/f2621f1e-b06d-4b2a-9116-3eecf4cc5ff7?hdnts=exp=1686269487~hmac=6057d794b5e7a38b7c9ccb47648b31fb5a282014fc7ec0ecf88f65ea684c954b","langPackModelVer":"","langPackModelUri":"","roomId":"","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"18252","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RB-P:HIT-SP:HITWIFI"}`

Thank you !

**Comment by nVuln** [comment]
sorry I can't help this device for some reason:
* this device is using thinq1 (old platform), my plugin support thinq2 device only
* homekit don't have native vacuum cleaner accessory, if I try to implement, it will be not work perfectly like native apps (ex: homekit can't do Start, Pause and Resume, or request robot go back to dock, or clean in selected zone)

**Comment by Slavitacus** [comment]
Okay, I understand.

Thanks anyway !

:-)
