### ISSUE TITLE
Refrigerator Door is always Open

### ISSUE THREAD

**Issue by mahmoud-os93** [nVuln/homebridge-lg-thinq#150]
**Describe The Bug:**
Refrigerator Door is always Open and is not reflecting real status

**To Reproduce:**
After adding the plugin

**Expected behavior:**
To reflect the real status of the door, and if doesn't work for some models, a way to disable this specific accessory

**Plugin Config:**

```
   "thinq1": true,
    "devices": [
        {
            "id": "998c7a70-b96f-11e9-b197-7440be26311a",
            "name": "Refrigerator",
            "type": "REFRIGERATOR",
            "ref_express_freezer": true,
            "ref_express_fridge": true,
            "ref_eco_friendly": true
        },
        {
            "id": "aa9c7590-b96f-11e9-8a99-203dbdb803a5",
            "name": "Washer",
            "type": "WASHER",
            "washer_trigger": true,
            "washer_door_lock": true
        }
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/85693689/161038003-60773c3f-b484-43bf-bfa9-e25021438580.png)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  v1.4.0
* **Node.js Version**:  v16.14.0
* **NPM Version**:  v8.3.1
* **Operating System**:

**Comment by nVuln** [comment]
> some collected logs :)
> 
> [Refrigerator homebridge logs.txt](https://github.com/nVuln/homebridge-lg-thinq/files/8390759/Refrigerator.homebridge.logs.txt)

seem your refrig using thinq 1 platform and it's not working correctly, I'll disable door sensor on thinq1, please try install `v1.2.15-test.5` and clear all cached accessories

**Comment by mahmoud-os93** [comment]
> 

Hi,
silly question, how can I install this version as it was not published yet ?

**Comment by nVuln** [comment]
> Hi, silly question, how can I install this version as it was not published yet ?

select `Install Previous Version` in Plugins
<img width="449" alt="Screen Shot 2022-04-01 at 7 41 35 PM" src="https://user-images.githubusercontent.com/54855446/161265720-7e33acb9-8a8f-4737-a251-f7bbc129b16c.png">

**Comment by mahmoud-os93** [comment]
Hi again,
having another issue with my refrigerator:
Almost everyday I get in the home app: this accessory is not responding, what is weird is that when I enter the LG app, the device somehow refreshes and it responds back in Homekit. Have you encountered this before ? is it related to Homekit/homebridge or a known LG app/server issue ?

**Comment by nVuln** [comment]
> Hi again, having another issue with my refrigerator: Almost everyday I get in the home app: this accessory is not responding, what is weird is that when I enter the LG app, the device somehow refreshes and it responds back in Homekit. Have you encountered this before ? is it related to Homekit/homebridge or a known LG app/server issue ?

I heard this issue from another people too, but I don't have thinq1 device to keep tracking this, look like it's problem from thinq1 server, all my devices using thinq2 and it's worked fine all time
currently I'll noted your response and keep investigate it, sorry about this problem
