### ISSUE TITLE
[LGThinQ] No ThinQ devices in your account.

### ISSUE THREAD

**Issue by grashkovan** [nVuln/homebridge-lg-thinq#153]
**Describe Your Problem:**
After changing the password of my LG account, I stop seeing any devices in the HomeBridge: 
[LGThinQ] No ThinQ devices in your account.
In addition, the following message is popping out every time when restarting the HomeBridge:
 [LGThinQ] Please open the native LG App and sign in to your account to see what happened, maybe new agreement need your accept. Then try restarting Homebridge.

**Logs:**
[4/6/2022, 10:35:53 AM] [LGThinQ] Please open the native LG App and sign in to your account to see what happened, maybe new agreement need your accept. Then try restarting Homebridge.
[4/6/2022, 10:35:53 AM] [LGThinQ] No ThinQ devices in your account.

[4/6/2022, 10:35:53 AM] [LGThinQ] Please open the native LG App and sign in to your account to see what happened, maybe new agreement need your accept. Then try restarting Homebridge.
[4/6/2022, 10:35:53 AM] [LGThinQ] No ThinQ devices in your account.

**Plugin Config:**

Show your Homebridge config.json here, remove any sensitive information.
{
            "auth_mode": "account",
            "password": "*******",
            "language": "en-US",
            "country": "US",
            "platform": "LGThinQ",
            "refresh_interval": 30,
            "refresh_token": "****************************************",
            "username": "rashkovan@gmail.com",
            "thinq1": true,
            "devices": [
                {
                    "id": "89e8f775-e387-1e34-8d2f-f8b95a9405ea",
                    "name": "LG Refrigerator",
                    "type": "REFRIGERATOR",
                    "serial_number": "101KRMK41779",
                    "washer_door_lock": false,
                    "ac_air_quality": true,
                    "ac_temperature_sensor": true,
                    "ac_led_control": true,
                    "ref_express_freezer": true,
                    "ref_express_fridge": true,
                    "ref_eco_friendly": true
                },
                {
                    "id": "A24D2550-09CD-4399-A609-59380F5606CB",
                    "name": "LG DRYER",
                    "type": "DRYER",
                    "serial_number": "901KWJU91700",
                    "washer_trigger": true,
                    "washer_door_lock": true
                },
                {
                    "id": "D854E315-CE48-455D-AD60-F5F0D9BDF983",
                    "name": "LG WASHER",
                    "type": "WASHER",
                    "serial_number": "901VWDN48346",
                    "washer_trigger": true,
                    "washer_door_lock": true
                }```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.2.14
* **Homebridge Version**: v1.4.0
* **Node.js Version**: v16.13.1
* **NPM Version**: v8.5.2
* **Operating System**: CentOS Linux release 8.5.2111

**Comment by iammanpreetsingh** [comment]
How did you fixed this?
