### ISSUE TITLE
ThinQ API is not ready. Please check configuration and try again.

### ISSUE THREAD

**Issue by town3r** [nVuln/homebridge-lg-thinq#157]
Started getting this error tonight.
No new agreements to accept. Reset password and got a new auth token.
Still no luck. :(

**Comment by nVuln** [comment]
some people got same issue, please try create new account, then invite them to old account

**Comment by nVuln** [comment]
or you can try install latest test version `v1.2.15-test.7`, I added some code to handle that issue, but not sure it's worked on your account

**Comment by town3r** [comment]
![image](https://user-images.githubusercontent.com/12396203/165297356-6d372ae6-eb1d-48e2-82cd-470cb7c089e5.jpeg)

**Comment by town3r** [comment]
New Account didn't seem to work on the existing installation of the plugin.

Uninstalling and Reinstalling the plugin and using the new Account seemed to solve the issue.

**Comment by vfontes** [comment]
> New Account didn't seem to work on the existing installation of the plugin.
> 
> Uninstalling and Reinstalling the plugin and using the new Account seemed to solve the issue.

I second this, even with the latest plugin version I still had to:
1. Create a new account (thanks, LG _sigh_).
2. Uninstall homebridge-lg-thinq and restart homebridge.
3. Delete homebridge-lg-thinq's cached accessories.
4. Install homebridge-lg-thinq again, and restart homebridge one last time.

Only after all that I was able to get my thinqv1 devices working again.
