### ISSUE TITLE
Window air conditioner request support

### ISSUE THREAD

**Issue by VoltIcaRus** [nVuln/homebridge-lg-thinq#165]
**Which device do you want to add? Please describe:**

Yeah! This is a new product! https://www.lge.co.kr/air-conditioners?subCateId=CT50114000
This new window air conditioner started selling in May and is now in June.
Korean customers are receiving the product.

But I need a button for this product for better homekit control.

**Describe the solution you'd like:**

First of all, this product does not have an auto mode function.
That's right, if you set this awesome plugin by default, you'll see
There is no need for the default button auto mode function.
I need to disable this button

Additional mods that need support
  Need to implement dehumidification blowing mode
Especially in the dehumidification mode, the error log keeps coming up?? (Not sure)

to check in debug mode
{"airState.opMode":0,  :  cooling (normal operation)
{"airState.opMode":1,  : dehumidify (no button)
{"airState.opMode":2,  : blow (no button)

What to do with the button
Quiet mode (airState.miscFuncState.silentAWHP) and 
ice cool power mode (airState.wMode.jet) buttons are implemented.
Additionally, an energy save mode (airState.powerSave.basic) button is also required.

And the error keeps coming up, I don't know why this is popping up

**Device Data:**

Device data:  {"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","deviceType":401,"modelName":"WINF_056905_WW","subModelNm":null,"sensorType":null,"alias":"에어컨","deviceCode":"AI01","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"WINF_TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"*****","timezoneCode":"Asia/Seoul","timezoneCodeAlias":"Korea/Seoul","sdsGuide":"","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"2331832","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20220608025913000","regIndex":0,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":{"airState.windStrength":6,"airState.bellSound.control":0,"airState.tempState.unit":0,"airState.diagCode":0,"airState.lightingState.displayControl":0,"airState.wDir.hStep":100,"mid":12559762,"airState.energy.onCurrent":394,"deviceContentsStatus":{"deactivated":["401-27-7","401-27-8"],"activated":["401-27-5","401-27-6"]},"airState.quality.sensorMon":0,"airState.tempState.target":18,"airState.miscFuncState.autoDryRemainTime":0,"airState.operation":1,"airState.fota.check":0,"airState.wMode.jet":0,"timestamp":1654696760655,"airState.powerSave.basic":0,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"KR"},"airState.tempState.current":23.5,"packageId":"RAC03024381220143812501","airState.reservation.sleepTime":0,"airState.melody":5,"airState.miscFuncState.childLock":0,"airState.miscFuncState.autoDry":255,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"kZLz4FHfT72yvVHvBwVCBA"},"airState.miscFuncState.silentAWHP":1,"online":true,"airState.opMode":0,"airState.reservation.targetTimeToStop":0,"airState.tempState.step":0},"manufacture":{"inventoryOrg":"DGZ","macAddress":"4C:BA:D7:F5:6B:4A","manufacturedAt":"2022-05-31T03:05:15.000000+0000","salesModel":"WQ05DCWDN.AKOR","manufactureModel":"WQ05DCWDN.AKOR","registeredAt":"2022-05-31T03:20:35.084882+0000","serialNo":"205KAPB1L664"},"online":true,"platformType":"thinq2","homeDeviceOrder":1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.11","modelJsonUri":"https://objectcontent.lgthinq.com/f693c785-8ea4-4125-af19-2f7d0a5e8338?hdnts=exp=1717730163~hmac=056850bfbbfa5f11238ecaf0ba4383f4f9db07add8d5245b11eeb846a8646f86","appModuleVer":"17.78","appModuleUri":"https://objectcontent.lgthinq.com/6f9e5106-2098-4fff-8382-44224a29519d?hdnts=exp=1701394617~hmac=5b9c7381ced9740f199fbe379f86226fcb0dd261953164fbfed15b0d1bf63b7e","appRestartYn":"Y","appModuleSize":"12867303","langPackProductTypeVer":"65.9","langPackProductTypeUri":"https://objectcontent.lgthinq.com/927cf241-1f6b-4919-9b0c-a7077d155847?hdnts=exp=1715935999~hmac=f7cf245e469a4b7aa7c27a2dc616ba02f88f0074c697d3cd63c9d6ad16096fc4","langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":[{"checksum":"0000AECA","partNumber":"SAA43812201","order":5},{"checksum":"00000880","partNumber":"SAA43812501","order":4},{"checksum":"00004C56","partNumber":"SAA43664301","order":3},{"checksum":"00006576","partNumber":"SAA43664601","order":2},{"checksum":"0000DEE0","partNumber":"SAA43664801","order":1}],"modemInfo":{"modelName":"WINF_056905_WW","appVersion":"clip_ble_v1.9.165","modemType":"RTK_RTL8720cm","ruleEngine":"y","size":2097152,"schedFota":"y","oneshot":"y"},"existsEntryPopup":"N","fwVer":null,"modemVer":null,"subDeviceCount":0,"firebaseLogKey":null,"cardType":"Large","cardControl":"Control","detailDeviceCode":null,"upgradableYn":"Y","autoFwDownloadYn":"Y"}

This is the error log

[6/8/2022, 11:50:27 PM] [LGThinQ] [에어컨] Received snapshot:  {"airState.opMode":1,"airState.powerSave.basic":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"m3BwnEWYSh-qNwhxauBReA"},"mid":15626272,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1654699827284}
[6/8/2022, 11:50:27 PM] [homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic was supplied illegal value: number 1 exceeded minimum of 2. See https://git.io/JtMGR for more info.
[6/8/2022, 11:50:27 PM] [homebridge-lg-thinq] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1982:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1415:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:481:35)
    at AirConditioner.updateAccessoryCharacteristic (/homebridge/node_modules/homebridge-lg-thinq/src/devices/AirConditioner.ts:227:20)
    at AirConditioner.update (/homebridge/node_modules/homebridge-lg-thinq/src/baseDevice.ts:33:10)
    at EventEmitter.emit (node:events:390:28)
    at /homebridge/node_modules/homebridge-lg-thinq/src/platform.ts:208:23
    at DeviceClient.<anonymous> (/homebridge/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:276:9)
    at DeviceClient.emit (node:events:390:28)
[6/8/2022, 11:50:27 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":1,"airState.powerSave.basic":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"m3BwnEWYSh-qNwhxauBReA"},"mid":15626272,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1654699827284}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}

Thank you so much for providing a great plugin!

**Comment by shonsj** [comment]
Hi Mate. I was going to request to add same device. But don't know how to get the device date. Could you please let me know how to get the info?

**Comment by VoltIcaRus** [comment]
> Hi Mate. I was going to request to add same device. But don't know how to get the device date. Could you please let me know how to get the info?

Device date?
Can you tell me what it is?
Debugging can be enabled in HB settings.

**Comment by shonsj** [comment]
Sorry mate. Its typo. I meant the device data
> > Hi Mate. I was going to request to add same device. But don't know how to get the device date. Could you please let me know how to get the info?
> 
> 
> 
> Device date?
> 
> Can you tell me what it is?
> 
> Debugging can be enabled in HB settings.
> 
>

**Comment by nVuln** [comment]
@VoltIcaRus I'll added all button based on opMode value in future update (auto, dry, fan), and it can configurable in plugin setting
for Quiet mode and energy save mode I'll added for your model `WINF_056905_WW` only
wait for future update

> Sorry mate. Its typo. I meant the device data
> 
> > > Hi Mate. I was going to request to add same device. But don't know how to get the device date. Could you please let me know how to get the info?
> > 
> > 
> > Device date?
> > Can you tell me what it is?
> > Debugging can be enabled in HB settings.

you can turn on homebridge debug mode and found device data in debug logging
<img width="453" alt="homebridge debug mode" src="https://user-images.githubusercontent.com/54855446/173211584-0de18ae0-2334-4f0b-a0bf-adf1f0a553a0.png">

**Comment by VoltIcaRus** [comment]
> @VoltIcaRus I'll added all button based on opMode value in future update (auto, dry, fan), and it can configurable in plugin setting for Quiet mode and energy save mode I'll added for your model `WINF_056905_WW` only wait for future update
> 
> > Sorry mate. Its typo. I meant the device data
> > > > Hi Mate. I was going to request to add same device. But don't know how to get the device date. Could you please let me know how to get the info?
> > > 
> > > 
> > > Device date?
> > > Can you tell me what it is?
> > > Debugging can be enabled in HB settings.
> 
> you can turn on homebridge debug mode and found device data in debug logging <img alt="homebridge debug mode" width="453" src="https://user-images.githubusercontent.com/54855446/173211584-0de18ae0-2334-4f0b-a0bf-adf1f0a553a0.png">

thx. bro! 
It will be of great help! Thank you so much
The led control and wind direction designation are good, but
It was troublesome because I couldn't control the quiet mode.

**Comment by nVuln** [comment]
I already published `v1.2.16-test.2` for your request, please try it

**Comment by VoltIcaRus** [comment]
Dry mode: work
Fan mode: work
Zet mode: not work

Dry mode off : not working back cool mode               (log: [LGThinQ] Set target AC mode =  undefined )
Fan mode off : not working back cool mode          (log: [LGThinQ] Set target AC mode =  undefined )


Two auto mode switches were created, so I briefly looked at the source file.
 I saw that I added a button assignment setting in the hb config file and tried to find it, but I got an error and put it on hold.

What I need is dry and fan mode, low noise mode, jet mode, energy saving mode, so the settings I tried are like this
"devices": [
                {
                    "id": "fb999851-ca81-1fa7-93df-4cbad7f56b4a",
                    "name": "에어컨",
                    "type": "AC",
                    "ac_mode": "COOLING",
                    "ac_swing_mode": "HORIZONTAL",
                    "ac_temperature_sensor": true,
                    "ac_humidity_sensor": false,
                    "ac_led_control": true,
                    "ac_fan_control": true
					"ac_buttons" : [
					{
						'name': 'Dry mode',
						'op_mode': 1,
					},
					{
						'name': 'Fan mode',
						'op_mode': 2,
					}
					]
                }
            ],

So there are two switches named auto mode.
One of the two is unresponsive and no log is generated.
The other one generates an error log.

Jet mode switch does not work even when activated and no logs are generated
Is there anything I can try?

Quiet mode and energy saving mode were not found

error log(auto mode switch off ):
[error log .txt](https://github.com/nVuln/homebridge-lg-thinq/files/8885854/error.log.txt)

**Comment by nVuln** [comment]
@VoltIcaRus I fixed some bug in `v1.2.16-test.3`, please help me test it

**Comment by nVuln** [comment]
> However, it seems strange that even though a log indicating that the target ac mode is set to 0, it does not switch to cool mode.

no error log? and device still not changed back to cool mode anyway?

**Comment by VoltIcaRus** [comment]
> > > However, it seems strange that even though a log indicating that the target ac mode is set to 0, it does not switch to cool mode.
> > 
> > 
> > no error log? and device still not changed back to cool mode anyway?
> 
> ![ninetail 2022-414](https://user-images.githubusercontent.com/3735740/173349519-faaf4208-671f-4595-ba61-aef35ee6fcac.gif) [ ](https://user-images.githubusercontent.com/3735740/173349519-faaf4208-671f-4595-ba61-aef35ee6fcac.gif) ![ninetail 2022-414](https://user-images.githubusercontent.com/3735740/173349519-faaf4208-671f-4595-ba61-aef35ee6fcac.gif) [ ](https://user-images.githubusercontent.com/3735740/173349519-faaf4208-671f-4595-ba61-aef35ee6fcac.gif) This is the operation of turning off the dry switch in dry mode.
> 
> Yes no error log, that's all
> 
> Does not return to cool mode

Oh I try switching from jet mode to dry mode
I found the error log
[not working back cool mode error log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/8890927/not.working.back.cool.mode.error.log.txt)

**Comment by VoltIcaRus** [comment]
I found the condition for the log to appear
If the air conditioner temperature is raised to 23 or higher in HomeKit control, it is indicated that the temperature is being raised.
Conversely, when HomeKit indicates that the temperature is lowering, only the 
[LGThinQ] Set target AC mode = 0 
log is displayed and does not change to cool mode.

**Comment by VoltIcaRus** [comment]
This is the log that appears when the controller operates dry ->fan->cool


[6/13/2022, 10:05:00 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":0,"airState.tempState.target":18,"meta":{"allDeviceInfoUpdate":false,"messageId":"RGD8_qd0ROeKy8dLx9Yxkw"},"mid":441292660,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125499943}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}
[6/13/2022, 10:05:00 PM] [LGThinQ] [에어컨] Received snapshot:  {"airState.opMode":1,"airState.tempState.target":23,"meta":{"allDeviceInfoUpdate":false,"messageId":"9RWFDh45RcuR907ked5LmQ"},"mid":441293479,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125500867}
[6/13/2022, 10:05:00 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":1,"airState.tempState.target":23,"meta":{"allDeviceInfoUpdate":false,"messageId":"9RWFDh45RcuR907ked5LmQ"},"mid":441293479,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125500867}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}
[6/13/2022, 10:05:07 PM] [LGThinQ] [에어컨] Received snapshot:  {"airState.opMode":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"TqYK9HM6RRCOK5wQacbzzg"},"mid":441300426,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125507704}
[6/13/2022, 10:05:07 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"TqYK9HM6RRCOK5wQacbzzg"},"mid":441300426,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125507704}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}
[6/13/2022, 10:05:12 PM] [LGThinQ] [에어컨] Received snapshot:  {"airState.opMode":0,"airState.tempState.target":18,"meta":{"allDeviceInfoUpdate":false,"messageId":"ySmqGxWQRRahC-k6j0oX8A"},"mid":441305182,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125512428}
[6/13/2022, 10:05:12 PM] [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":0,"airState.tempState.target":18,"meta":{"allDeviceInfoUpdate":false,"messageId":"ySmqGxWQRRahC-k6j0oX8A"},"mid":441305182,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655125512428}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}

**Comment by nVuln** [comment]
I added some debug code in `v1.2.16-test.4`, please try again and let see

**Comment by VoltIcaRus** [comment]
If I change the fan speed in fan mode, an error log occurs, but changes fan speed normally. (0103)

Still does not change from dry fan mode to cool mode


Dry mode off
[LGThinQ] Set button  Dry mode , opMode =  1
[LGThinQ] Set target AC mode =  0

Fan mode on 
[LGThinQ] Set button  Fan mode , opMode =  2
[LGThinQ] Set AC OpMode =  2
[LGThinQ] mqtt message received: {"controlResult":{"messageId":"n95Fo883N7fHVd0LKSzjqC","deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","returnCode":"0000"}}
 [LGThinQ] [request] post https://kic-service.lgthinq.com:46030/v1/service/devices/fb999851-ca81-1fa7-93df-4cbad7f56b4a/control-sync
 [LGThinQ] [에어컨] Received snapshot:  {"airState.opMode":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"skTqBzFpRaSAVFORStlX_A"},"mid":490124870,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655174332929}
 [LGThinQ] mqtt message received: {"data":{"state":{"reported":{"airState.opMode":2,"meta":{"allDeviceInfoUpdate":false,"messageId":"skTqBzFpRaSAVFORStlX_A"},"mid":490124870,"online":true,"static":{"countryCode":"KR","deviceType":"401"},"timestamp":1655174332929}}},"deviceId":"fb999851-ca81-1fa7-93df-4cbad7f56b4a","type":"monitoring"}


Fan mode off
[LGThinQ] Set button  Fan mode , opMode =  2
[LGThinQ] Set target AC mode =  0

no good ideas come to mind

**Comment by nVuln** [comment]
@VoltIcaRus my mistake, forgot send request to change opMode value when button OFF 🥲, please try again `v1.2.16-test.5`

**Comment by VoltIcaRus** [comment]
@nVuln 
cool! Really cool! It works perfectly!
Really good job! Can I start my cool summer automation
Thank you so much!

**Comment by nVuln** [comment]
> @nVuln Cool! Really cool! It works perfectly! Really good job! I can start my cool summer automation Thank you so much!

thanks so much for your help, you can keep using this test version until next release
