### ISSUE TITLE
LG Airtower purifier not supported

### ISSUE THREAD

**Issue by aaronjh91** [nVuln/homebridge-lg-thinq#167]
**Which device do you want to add? Please describe:**

LG air purifiers are supposed to be supported but the new AirTower Air Purifiers are showing as not supported
**Describe the solution you'd like:**
Would like control of the AirtTower Air Purifier

**Device Data:**

6/13/2022, 3:29:11 PMLg Thinq starting
6/13/2022, 3:29:21 PMLg ThinqLoaded plugin 'homebridge-lg-thinq'
6/13/2022, 3:29:21 PMLg ThinqLoading 1 platforms...
6/13/2022, 3:29:21 PMLg ThinqBridge is running on port 51876.
6/13/2022, 3:29:28 PMLg ThinqLGThinQSuccessfully connected to the ThinQ API.
6/13/2022, 3:29:29 PMLg ThinqLGThinQ[Washer] Setting up device!
6/13/2022, 3:29:30 PMLg ThinqLGThinQAdding new accessory: 68b31963-3d9f-1a26-ac13-402f867c06c7: Washer (WASHER F3M2CYK__)
6/13/2022, 3:29:30 PMLg ThinqLGThinQ[Living Room Air Purifier] Setting up device!
6/13/2022, 3:29:31 PMLg ThinqLGThinQDevice not supported: 92423c23-51c5-1a9e-a43f-64cbe935d972: Living Room Air Purifier (undefined FS151PBB1.AWHEUS)
6/13/2022, 3:29:31 PMLg ThinqLGThinQ[Dryer] Setting up device!
6/13/2022, 3:29:32 PMLg ThinqLGThinQAdding new accessory: b758b78a-8960-1651-843d-402f86c399d3: Dryer (DRYER RV13D5JSD_D_US)
6/13/2022, 3:29:32 PMLg ThinqLGThinQ[Master Bedroom Air Purifier] Setting up device!
6/13/2022, 3:29:33 PMLg ThinqLGThinQDevice not supported: c6588ab1-cb16-1766-8372-64cbe93ef05e: Master Bedroom Air Purifier (undefined FS151PBB1.AWHEUS)
6/13/2022, 3:29:33 PMLg ThinqLGThinQStart MQTT listener for thinq2 device
6/13/2022, 3:29:47 PMLg ThinqLGThinQSuccessfully connected to the MQTT server.

**Comment by nVuln** [comment]
you mean aerotower? I'm still working on it, please turn on homebridge debug mode and upload some device data, it's may useful
