### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by DeIeK** [nVuln/homebridge-lg-thinq#169]
Hello.
I can not find how disable auto mode and other AC buttons?
I would like to disable this in homekit

Environment:

Plugin Version: 1.2.16
Homebridge Version: 1.4.0
Node.js Version: 16.13.1
NPM Version: 8.1.2
Operating System: Raspbian 10.3

**Comment by nVuln** [comment]
> Hello, removing doesn’t work.

show me your plugin config

**Comment by mb200k** [comment]
I tried it and also can disable everything but jet mode and auto mode... I would like to leave only thermostat. I tried even removing the plugin entirely and reinstalling, all configs from zero, no ac button on config and still shows jet mode and auto on HomeKit app

**Comment by modestindustries** [comment]
I'm seeing this too. Config looks like this:

` {
            "platform": "LGThinQ",
            "auth_mode": "token",
            "refresh_token": "REDACTED",
            "country": "CA",
            "language": "en-CA",
            "thinq1": true,
            "devices": [
                {
                    "id": "REDACTED",
                    "name": "LoG",
                    "type": "AC",
                    "ac_mode": "COOLING",
                    "ac_swing_mode": "VERTICAL",
                    "ac_temperature_sensor": false,
                    "ac_fan_control": true,
                    "ac_buttons": []
                }
            ],
            "refresh_interval": 60,
            "_bridge": {
                "username": "REDACTED",
                "port": REDACTED
            }
        }`

**Comment by gabpaladino** [comment]
Same here

**Comment by modestindustries** [comment]
Thank you for removing the default buttons in [AirConditioner.ts](https://github.com/nVuln/homebridge-lg-thinq/blob/master/src/devices/AirConditioner.ts).

Could this also be done in the thinq1 version?

**Comment by DeIeK** [comment]
Auto mode disappeared - but appeared Jet mode button?
How disable Jet mode? Is it even possible?

Plugin Version: 1.2.17
