### ISSUE TITLE
AC shows an additional switch in HomeKit

### ISSUE THREAD

**Issue by K0ciq** [nVuln/homebridge-lg-thinq#176]
First of all, thank you for the amazing work you're doing with this plugin!

I have one question/request. 

Is there any way to disable the "Power" switch in HomeKit?

I prefer to use HomeKit just to set cooling/heating and target temperature. For anything else I prefer to use the remote that came with the AC. 

Is there any way to achieve this? I have unchecked all options on Homebridge but it still appears there. 

Model: LG PC12S1

![image](https://user-images.githubusercontent.com/91679198/176723034-af4f2626-2eb9-4c31-8157-6226208594b6.jpeg)

![image](https://user-images.githubusercontent.com/91679198/176723194-fb348541-0f21-4a07-8378-2b102f87ec4d.jpeg)

**Comment by nVuln** [comment]
try clean cached accessories in homebridge setting page
