### ISSUE TITLE
indoor temperature Not updating

### ISSUE THREAD

**Issue by moguennouni** [nVuln/homebridge-lg-thinq#177]
Hello,
First thank you for this magical plugin, it changed the way I use my LG AC.
As wrote on the title the indoor temp is not updating automatically in home app. So I need to open The LG ThinQ app to get it updated.
Is there a way to make it do it because we can't create a automation with temperature as a condition.
Thank you

**Comment by nVuln** [comment]
which plugin version did you used ?

**Comment by moguennouni** [comment]
Hello,

The last one I guess 

homebridge-lg-thinq v1.2.17

Thx

**Comment by FilipAben** [comment]
Having the same problem here. When opening the ThinQ app, an update seems to be triggered
v1.2.17

**Comment by FilipAben** [comment]
Some more observations after enabling debug logging:
1. the MQTT listener (thinq2 here) never receives any data, even though I'm switching the AC on/off and changing settings through the ThinQ app.
2. the code requests a snapshot every 10 minutes, but the data is outdated as it contains a timestamp which was hours ago.
3. after I open the ThinQ app, next snapshot requested by the plugin contains up-to-date data with a timestamp set to around the time I opened the app.

**Comment by vfontes** [comment]
Can confirm the same thing occurs for me, I'm on version 1.2.17.

**Comment by corvel** [comment]
Did you guys resolve that issue? It would be nice to make this working.

**Comment by Damien514** [comment]
Same issue here. I never the correct data, from both my Thinq1 and Thinq2 AC. Any way to "ping" the device to force update the temperature?

**Comment by nVuln** [comment]
> Same issue here. I never the correct data, from both my Thinq1 and Thinq2 AC. Any way to "ping" the device to force update the temperature?

unfortunately I don't have any thinq1 device right here to try 🥲

**Comment by aabdellah** [comment]
Having the same issue as well

**Comment by aabdellah** [comment]
After investigating the traffic between ThinQ app and their servers, I have found out that temps have to be updated using a call to /control endpoint on each AC device so that the temperature will be updated in further calls to /service/homes.

Below is the details of the endpoint:
```
POST https://eic-service.lgthinq.com:46030/v1/service/devices/{deviceId}/control
{
    "command": "Set",
    "ctrlKey": "allEventEnable",
    "dataKey": "airState.mon.timeout",
    "dataValue": "70"
}
```

Is it possible to call this endpoint periodically for devices that have temperature sensors? this will greatly improve automations for AC.

ThinQ app calls the endpoint for each AC device every minute to update the temperature.

**Comment by nVuln** [comment]
> After investigating the traffic between ThinQ app and their servers, I have found out that temps have to be updated using a call to /control endpoint on each AC device so that the temperature will be updated in further calls to /service/homes.
> 
> Below is the details of the endpoint:
> 
> ```
> POST https://eic-service.lgthinq.com:46030/v1/service/devices/{deviceId}/control
> {
>     "command": "Set",
>     "ctrlKey": "allEventEnable",
>     "dataKey": "airState.mon.timeout",
>     "dataValue": "70"
> }
> ```
> 
> Is it possible to call this endpoint periodically for devices that have temperature sensors? this will greatly improve automations for AC.
> 
> ThinQ app calls the endpoint for each AC device every minute to update the temperature.

nice, let me work on it
thanks for your works

**Comment by nVuln** [comment]
I just added it in `1.6.4-ac.1`, can anyone pull it and test?

**Comment by moguennouni** [comment]
Hello , just installed the test version and it seems to work!
It's updating the temperature continuously 
Thank you for this amazing work !

**Comment by nVuln** [comment]
need a few more test before I can merge it into stable

**Comment by vfontes** [comment]
Working here as well!
