### ISSUE TITLE
humitity sensor could not get data

### ISSUE THREAD

**Issue by sangdonyeom** [nVuln/homebridge-lg-thinq#190]
**Describe The Bug:**

LG Thinq app displayed humidity and temperature data all time when it can display it is off
but 'Homebridge' can display only temperature data, humidity is always '0'.
**To Reproduce:**

 humidity is always '0'
**Expected behavior:**

humidity value display in Homebridge.
**Logs:**
This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
```
Show the Homebridge logs here (make sure homebridge DEBUG mode is turned `on`), remove any sensitive information.
```

**Plugin Config:**

```
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "country": "KR",
    "language": "ko-KR",
    "auth_mode": "account",
    "refresh_token": "*************",
    "username": "*************",
    "password": "*************",
    "devices": [
        {
            "id": "*************",
            "name": "우리집 세탁기",
            "type": "WASHER"
        },
        {
            "id": "*************",
            "name": "식기세척기",
            "type": "DISHWASHER"
        },
        {
            "id": "*************",
            "name": "우리집 미니세탁기",
            "type": "WASHER"
        },
        {
            "id": "*************",
            "name": "에어컨",
            "type": "AC",
            "ac_air_quality": true,
            "ac_mode": "COOLING",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": true,
            "ac_fan_control": false
        },
        {
            "id": "*************",
            "name": "벽걸이 에어컨",
            "type": "AC",
            "ac_air_quality": false,
            "ac_mode": "COOLING",
            "ac_swing_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": false,
            "ac_fan_control": false
        },
        {
            "id": "**************",
            "name": "의류건조기",
            "type": "DRYER"
        }
    ],
    "thinq1": true,
    "refresh_interval": 60,
    "platform": "LGThinQ",
    "_bridge": {
        "username": "**********",
        "port": *************
    }
}
**Screenshots:**

![image](https://user-images.githubusercontent.com/59303198/193409623-b86af604-d75d-4b60-9f24-e472f10cfab9.png)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by nVuln** [comment]
I already fixed it on `v1.2.19`, please check it
