### ISSUE TITLE
Washing machine remaining time not visible since iOS 16

### ISSUE THREAD

**Issue by florianbeer** [nVuln/homebridge-lg-thinq#191]
**Describe The Bug:**
Since iOS 16 the remaining washing machine time is not visible in the home app anymore.

Room view:
![IMG_1483AE2AACC9-1](https://user-images.githubusercontent.com/800047/193441417-7bff879e-534f-4101-982d-c8fda7b9a94a.jpeg)

Accessory view:
![IMG_F73D6D8EEF21-1](https://user-images.githubusercontent.com/800047/193441425-a985e35c-4e5a-46f6-a4ec-d81fd07d7c17.jpeg)

**Expected behavior:**
Screenshot from macOS Monterey (iOS 15 looked similar):
<img width="500" alt="Screenshot 2022-10-02 at 08 28 08" src="https://user-images.githubusercontent.com/800047/193441080-075b5eb2-ba10-4077-96cf-2a92a21258b8.png">

**Plugin Config:**

```
        {
            "country": "**",
            "language": "*****",
            "auth_mode": "token",
            "refresh_token": "******",
            "username": "****",
            "password": "*****",
            "devices": [
                {
                    "id": "****",
                    "name": "Washing Machine",
                    "type": "WASHER",
                    "washer_trigger": true,
                    "washer_door_lock": false
                }
            ],
            "thinq1": false,
            "refresh_interval": 60,
            "platform": "LGThinQ"
        }
```

**Environment:**

* **Plugin Version**: 1.2.18
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.17.0
* **NPM Version**: 8.15.0
* **Operating System**: Debian 10.13, hb-service 4.50.1

**Comment by kuroio** [comment]
I also have the same problem, I see the accessory only when it is in use, from the small valve icon, at the moment I solved it by putting it in my favorites, you can see them

**Comment by nVuln** [comment]
please try enable `washer_door_lock`, my washer still appear with door lock enabled

**Comment by florianbeer** [comment]
Indeed, if I activate `washer_door_lock` and "show as separate tiles" I can add the washer to my favourites and still see the time from there.

**Comment by ifeign** [comment]
This seems odd behavior, I’m curious - do any of you have any official HomeKit faucets or valves like the Eve Aqua? Surely these don’t disappear in ios16 - our LG accessory probably just needs to have its type changed , currently it’s behaving as a sensor not a standalone device

**Comment by nVuln** [comment]
following up in #196
