### ISSUE TITLE
Sensor only Refrigerator support

### ISSUE THREAD

**Issue by pospanet** [nVuln/homebridge-lg-thinq#193]
I am using this plug-in together with fridge and having temperature as thermostat setting is causing some difficulties with home automation.
So, I am wondering whether there might be a switch like "sensor only" for fridge exposing temperature really as sensor only with no modification allowed. Thanks

**Comment by nVuln** [comment]
Sorry I can't do this because I don't understand why you need that, thermostat is thermostat, people direct control desired temperature
and you can easy create a automation based on temperature of thermostat (similar temperature sensor)

btw, you can fork my plugin and make a custom
