### ISSUE TITLE
get token error

### ISSUE THREAD

**Issue by grenona** [nVuln/homebridge-lg-thinq#195]
when i try to add setting for LG account Login

i get this error

![2022-10-24_8-20-35](https://user-images.githubusercontent.com/88557992/197524611-61a96ec0-b48d-4f59-b5af-7bbf8a7b9fbd.jpg)

**Comment by nVuln** [comment]
more detail please, share plugin config, your account country

**Comment by grenona** [comment]
i found the issue i select Canada and it work fine  thanks
