### ISSUE TITLE
Warning "Current temperature"

### ISSUE THREAD

**Issue by diegomultiplicavc** [nVuln/homebridge-lg-thinq#208]
**Describe Your Problem:**

Warning: "This plugin threw an error from the characteristic 'Current Temperature': Characteristic Property 'minValue' must be a finite number, received "NaN" (string). See https://homebridge.io/w/JtMGR for more info."

**Plugin Config:**

{
            "country": "BR",
            "language": "pt-BR",
            "auth_mode": "token",
            "refresh_token": "xxx",
            "username": "xxx",
            "password": "xxx",
            "platform": "LGThinQ",
            "devices": [
                {
                    "id": "xxx",
                    "name": "AC xxx",
                    "type": "AC",
                    "ac_air_quality": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true
                },
                {
                    "id": "xxx",
                    "name": "AC xxx",
                    "type": "AC",
                    "ac_air_quality": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true
                },
                {
                    "id": "xxx",
                    "name": "AC xxx",
                    "type": "AC",
                    "ac_air_quality": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_fan_control": true
                },
                {
                    "id": "xxx",
                    "name": "AC xxx",
                    "type": "AC",
                    "ac_air_quality": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_fan_control": true
                },
                {
                    "id": "xxx",
                    "name": "AC xxx",
                    "type": "AC",
                    "ac_air_quality": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_fan_control": true
                }
            ],
            "thinq1": false,
            "refresh_interval": 60
        },

**Environment:**

* **Homebridge Version**: 1.6.0
* **Plugin Version**: 1.3.0
* **Node.js Version**: 18.12.1
* **NPM Version**: 8.19.2
* **Operating System**: Docker

**Comment by nVuln** [comment]
please turn on homebridge debug mode and provided some device data in debug logging
<img width="453" alt="homebridge debug mode" src="https://user-images.githubusercontent.com/54855446/210124145-3e56f205-5c75-4ad9-9cfd-e3889fa9995f.png">
