### ISSUE TITLE
LG AC setup support needed

### ISSUE THREAD

**Issue by T18DJ** [nVuln/homebridge-lg-thinq#210]
**Describe Your Problem:**
After using this plugin for a few months I would like to get it setup in the perfect way. It now has some buttons in the homekit app which do nothing / aren't named. I want to get rid of them or make them useful. Also the 'auto' mode is missing.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```
"country": "NL",
            "language": "nl-NL",
            "auth_mode": "token",
            "refresh_token": "xxxx  "username": "toxxxxx@.com",
            "password": "xxx-xxx-xxx",
            "devices": [
                {
                    "id": "75axxx",
                    "name": "Airco zolder",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true,
                    "ac_buttons": [
                        {
                            "name": "Cool",
                            "op_mode": 0
                        },
                        {
                            "name": "Energy saver",
                            "op_mode": 6
                        },
                        {
                            "name": "Fan",
                            "op_mode": 2
                        },
                        {
                            "name": "Dry",
                            "op_mode": 1
                        }
                    ]
                },
                {
                    "id": "e47xxxxx",
                    "name": "Airco woonkamer",
                    "type": "AC",
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": true,
                    "ac_humidity_sensor": false,
                    "ac_fan_control": true
                }
            ],
            "thinq1": false,
            "refresh_interval": 60,
            "platform": "LGThinQ"

```

**Screenshots:**
![image](https://user-images.githubusercontent.com/103461439/212702389-2e87f01a-ba1a-4694-936e-348adc29241a.jpeg)
![image](https://user-images.githubusercontent.com/103461439/212702624-9f1e99aa-c5e3-4f3c-b7fc-2f238720b90d.jpeg)
![image](https://user-images.githubusercontent.com/103461439/212702652-bc948875-3b3a-4412-ba6c-a27f0f9c4f44.jpeg)
**Environment:**

* **Plugin Version**: 1.3.0
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.13.2
* **NPM Version**: ?
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
1. `ac_buttons` setup is personalized each device, I just give an example, not sure it's worked on your device, to know `op_mode` value of feature you want, please turn on homebridge debug mode, try turn on/off that feature by remote, then see `op_mode` changed in debug logging
2. about button named label, it's ios 16 issue, you can manual renamed it, just clear accessory name on home app, homebridge name will appear as placeholder
3. auto mode can be configured by `ac_buttons` with correct op_mode value
