### ISSUE TITLE
Characteristic was supplied illegal value

### ISSUE THREAD

**Issue by cbeilman** [nVuln/homebridge-lg-thinq#211]
I'm receiving this message in the console:
This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 15.6 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.

**Comment by nVuln** [comment]
is your device using fahrenheit unit ?
can you upload some debug logging?

**Comment by cbeilman** [comment]
Yes, it is using Fahrenheit. How do I generate debug logs?

**Comment by nVuln** [comment]
> Yes, it is using Fahrenheit. How do I generate debug logs?

sorry for late reply, just back to work after vacation
you need turn on homebridge debug mode first
<img width="453" alt="homebridge debug mode" src="https://user-images.githubusercontent.com/54855446/215002330-98ad5207-3a3e-47a4-900f-5cdda8ac4eaa.png">
then restart it, device data should appear in debug logging
