### ISSUE TITLE
Log the consumption in kwh of an air conditioner

### ISSUE THREAD

**Issue by BenouGui** [nVuln/homebridge-lg-thinq#222]
Hello, 

Is it possible to retrieve the energy consumption of an AC air conditioning via API
If so would it be possible to implement this in your plugin?
to MQTT for example?

Thanks in advance

**Comment by nVuln** [comment]
if your LG thinq app have this feature, I can implement it
as my knowledge LG do not provide energy consumption via api, let me know if your device supported this feature

**Comment by BenouGui** [comment]
![IMG_0146](https://user-images.githubusercontent.com/72623517/224754951-742b3b7a-9ad5-4a86-9021-c708dca6ce0e.png)

![IMG_0147](https://user-images.githubusercontent.com/72623517/224755008-a3ed6d4f-73a4-475a-b816-4f91d585b119.png)

The log : 
13/03/2023, 16:47:48] [homebridge-lg-thinq] [ClimRezDeChaussee] Received snapshot:  **{"airState.energy.onCurrent":1592**,"meta":{"allDeviceInfoUpdate":false,"messageId":"9qSDIoBKR-2Bis7NzIGrZw"},"mid":859132896,"online":true,"static":{"countryCode":"BE","deviceType":"401"},"timestamp":1678722468102}
[13/03/2023, 16:47:48] [homebridge-lg-thinq] mqtt message received: {"data":{"state":{"reported":_{"airState.energy.onCurrent":1592,_"meta":{"allDeviceInfoUpdate":false,"messageId":"9qSDIoBKR-2Bis7NzIGrZw"},"mid":859132896,"online":true,"static":{"countryCode":"BE","deviceType":"401"},"timestamp":1678722468102}}},"deviceId":"34edf89f-a845-1b88-8baa-4cbce9cbd5c2","type":"monitoring"}


airState.energy.onCurrent":1592. ==> consumption live in Wh

**Comment by nVuln** [comment]
added it, will be available in next release

**Comment by BenouGui** [comment]
Hello, thank you very much, but it's a shame to have integrated this value only in the eve.app application
I never managed to export data from EVE other than on Eve
Other plugin (ex : https://github.com/grzegorz914/homebridge-enphase-envoy#readme) exports data to mqtt or influx db, is it possible to integrate?
my goal being to add the consumption of air conditioning in Grafana
thank you in advance for your response
