### ISSUE TITLE
AC humidity values incorrectly reporting 100%

### ISSUE THREAD

**Issue by kwridan** [nVuln/homebridge-lg-thinq#224]
**Describe The Bug:**

I recently Installed the plugin for use with LG Multi V Duct Air Conditioner unit and noticed the humidity values were being reported as 100%! 

**To Reproduce:**

- Install the plugin
- Configure to connect to LG and select a Multi V duck air conditioner
- Enable `ac_humidity_sensor` 
- Restart homebridge
- Notice the humidity values reported is 100%
- Notice the logs highlight it's attempting to set values larger than 100! 

**Expected behavior:**

- Humidity values should not exceed 100

**Logs:**

```
[homebridge-lg-thinq] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic was supplied illegal value: number 350 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.
```

In this example, the value being displayed on the AC indoor controller is `35%` - so looks like it's reporting it as `350` to ThinQ.

**Plugin Config:**

```
{
    "country": "GB",
    "language": "en-GB",
    "auth_mode": "token",
    "refresh_token": "***",
    "username": "",
    "password": "",
    "devices": [
        {
            "id": "***",
            "name": "AirCon",
            "type": "AC",
            "ac_air_quality": true,
            "ac_mode": "BOTH",
            "ac_temperature_sensor": true,
            "ac_humidity_sensor": true
        }
    ],
    "thinq1": false,
    "refresh_interval": 60,
    "platform": "LGThinQ"
}
```

**Screenshots:**

<img src="https://user-images.githubusercontent.com/11914919/228026185-b3692900-ae89-4ac0-8f8a-058451f096e2.jpeg" height="250px" />

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.3.0
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v16.14.2
* **Operating System**:  Docker 

**Possible Solutions**

I'm not sure if there's a better way to detect this, but looking at how the homeassistant thinq plugin handles this, it appears to check if the value is greater than 100 and divide by 10.  It looks like different AC units may not be consistent with how they report this value.

https://github.com/ollo69/ha-smartthinq-sensors/pull/279/files

Happy to open a PR if you think the above is a sufficient solution.

Thanks for working on this plugin 🙏

**Comment by nVuln** [comment]
fix it now, thanks for your report 🫡

**Comment by kwridan** [comment]
Thank you for applying the fix 🙏
