### ISSUE TITLE
Homebridge is throwing an error for Country Code 

### ISSUE THREAD

**Issue by jamesh773** [nVuln/homebridge-lg-thinq#228]
**Describe The Bug:**
Homebridge cannot send commands to LG devices and displays "This plugin threw an error from the characteristic 'Target Heater-Cooler State': Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'countryCode'). See https://homebridge.io/w/JtMGR for more info."

**To Reproduce:**
It happens just by being on and running. I receive the error any time I try to send a command to turn on my AC/heaters.

**Expected behavior:**
The AC/heater should turn on with no error.

**Logs:**

[4/20/2023, 11:34:14 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 1AEE) is running on port 51231.
[4/20/2023, 11:34:18 AM] [LGThinQ] Successfully connected to the ThinQ API.
[4/20/2023, 11:34:19 AM] [LGThinQ] [Office] Setting up device!
[4/20/2023, 11:34:20 AM] [LGThinQ] Restoring existing accessory: d12d2330-689e-11dc-ae03-044eaf40c89d: Office (AC RAC_056905)
[4/20/2023, 11:34:20 AM] [LGThinQ] Cannot read properties of undefined (reading 'countryCode')

**Plugin Config:**

{
    "country": "US",
    "language": "en-US",
    "auth_mode": "token",
    "refresh_token": "redacted",
    "username": "redacted",
    "password": "redacted",
    "devices": [
        {
            "id": "d12d2330-689e-11dc-ae03-044eaf40c89d",
            "name": "Office",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL"
        },
        {
            "id": "d27fd2a0-7149-11d3-80ca-044eaf398a15",
            "name": "Living Room",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL"
        },
        {
            "id": "d2810b20-7149-11d3-80d2-044eaf40c943",
            "name": "Bedroom",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_swing_mode": "VERTICAL"
        }
    ],
    "thinq1": true,
    "refresh_interval": 60,
    "platform": "LGThinQ"
}

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: homebridge-lg-thinq v1.4.1
* **Homebridge Version**: v1.6.0
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Synology NAS

**Comment by nVuln** [comment]
already fixed it in latest version, please update
