### ISSUE TITLE
Is this possible to disable Temperature/Thermostat with a fridge ?

### ISSUE THREAD

**Issue by Dandumontp** [nVuln/homebridge-lg-thinq#232]
Hi

I use the plug-in with a fridge and the temperature reported is the same as the temperature into the thermostat. Is this possible to disable the temperature and only keep the door sensor ?

When i demand the temperature to Siri, i have a weird response : between -18°C and the real value (on another sensor).

**Comment by nVuln** [comment]
this is refridgerator, not door sensor module, I can't customize it just for you
you can fork this repo and remove whatever you want

**Comment by Dandumontp** [comment]
No problme, thank you.
