### ISSUE TITLE
LG Washer/Drier - unconfigured button

### ISSUE THREAD

**Issue by Radon-iot** [nVuln/homebridge-lg-thinq#244]
How do I get rid of an unconfigured button showing up as accessory? What does it do anyway?

**Comment by mstislavm** [comment]
Same question

**Comment by SchubyTuesday** [comment]
Same question

**Comment by SchubyTuesday** [comment]
I figured out what this is. It is the "Tub Clean Coach". We need a

"tub_clean_coach": false

option in the config.

**Comment by nVuln** [comment]
if you turn off that button, valve tile will disappeared too due ios 16 problem, you cannot open it to see remaining time, all you can see is on/off status showed on top of Home app (sensor status)
so this button will always appear until I can found another solution to deal with it or Homekit release new accessory type matched with Washer/Dryer

**Comment by SchubyTuesday** [comment]
Is there a way to disable the API for the Tub Clean Coach from the HomeKit Accessory all together, similar to the Door Lock? The issue lies within how HomeKit handles it, so if you can have your accessory ignore that functionality all together it may work.

**Comment by nVuln** [comment]
> So you're saying that Tub Clean Coach is required for your plugin to function at all?
> 
> I don't blame you of course, as you are dealing with issues stemming from Apple and LG. If that's the case, then so be it. Hopefully, Apple or LG make updates that solve this problem.

valve tile need atleast 1 other accessory to display in home app, so programmable switch is best choice because people can easy ignore it, no miss click or anything else trouble
that button will be there until I can found another solution, or apple release homekit spec for washer/dryer (very very best case)
