### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Christian-CFP** [nVuln/homebridge-lg-thinq#25]
After starting the washer this error message appears constantly:

7.7.2021, 12:02:31TEST BridgeERROR[TEST Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)

In HK it shows that it is running but the remaining time is set 00:00

**Comment by nVuln** [comment]
please turn on homebridge debug mode, you can see device data in debug logging, upload it

**Comment by Christian-CFP** [comment]
Nothing there. Only this error.

**Comment by Christian-CFP** [comment]
All I see:

7.7.2021, 14:28:48LG ThinQ BridgeInitializing HAP-NodeJS v0.9.4...
7.7.2021, 14:28:49LG ThinQ BridgeLoaded plugin 'homebridge-lg-thinq'
7.7.2021, 14:28:49LG ThinQ BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
7.7.2021, 14:28:49LG ThinQ BridgeLoading 1 platforms...
7.7.2021, 14:28:49LG ThinQ BridgePreparing Advertiser for 'LG ThinQ Bridge 52DC' using bonjour-hap backend!
7.7.2021, 14:28:49LG ThinQ BridgeStarting to advertise 'LG ThinQ Bridge 52DC' using bonjour-hap backend!
7.7.2021, 14:28:49LG ThinQ BridgeBridge is running on port 52826.
7.7.2021, 14:28:52LG ThinQ BridgeLGThinQAdding new accessory: WASCHMASCHINE
7.7.2021, 14:28:52LG ThinQ BridgeERROR[WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)
7.7.2021, 14:28:52LG ThinQ BridgeLGThinQStart polling device data.
7.7.2021, 14:28:58LG ThinQ BridgeERROR[LG ThinQ Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)
7.7.2021, 14:29:03LG ThinQ BridgeERROR[LG ThinQ Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)
7.7.2021, 14:29:08LG ThinQ BridgeERROR[LG ThinQ Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)
7.7.2021, 14:29:13LG ThinQ BridgeERROR[LG ThinQ Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)
7.7.2021, 14:29:18LG ThinQ BridgeERROR[LG ThinQ Bridge 52DC@WASCHMASCHINE@WASCHMASCHINE@Remaining Duration] characteristic value expected valid finite number and received "NaN" (number)

**Comment by nVuln** [comment]
go to Homebridge Setting and turn on debug mode
<img width="433" alt="Screen Shot 2021-07-07 at 7 41 39 PM" src="https://user-images.githubusercontent.com/54855446/124760925-6e458580-df5b-11eb-9ea8-3adc4c4a739e.png">

**Comment by Christian-CFP** [comment]
I'm sorry. I am using HOOBS. V4 is just out and I have no clue how to activate homebridge -D (wich works with HOOBS V3).
In HOOBS there is no switch to activate the debug mode. So I have to wait until I got the answer to this from the HOOBS guys.

**Comment by Christian-CFP** [comment]
Here we go:

8.7.2021, 06:46:39LG ThinQ Bridge starting
8.7.2021, 06:46:41LG ThinQ BridgeInitializing HAP-NodeJS v0.9.4...
8.7.2021, 06:46:42LG ThinQ BridgeLoaded plugin 'homebridge-lg-thinq'
8.7.2021, 06:46:42LG ThinQ BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
8.7.2021, 06:46:42LG ThinQ BridgeLoading 1 platforms...
8.7.2021, 06:46:42LG ThinQ BridgeLGThinQExecuted didFinishLaunching callback
8.7.2021, 06:46:42LG ThinQ BridgePreparing Advertiser for 'LG ThinQ Bridge 52DC' using bonjour-hap backend!
8.7.2021, 06:46:42LG ThinQ BridgeSetup URI 'X-HM://0023ISYWY5JFH'
8.7.2021, 06:46:42LG ThinQ BridgeStarting to advertise 'LG ThinQ Bridge 52DC' using bonjour-hap backend!
8.7.2021, 06:46:42LG ThinQ BridgeBridge is running on port 52826.
8.7.2021, 06:46:46LG ThinQ BridgeLGThinQFound device:  0776fc24-e9de-1726-82d2-44cb8be1cfbe: WASCHMASCHINE (WASHER FH6G1BAPK2_WW_SPI)
8.7.2021, 06:46:46LG ThinQ BridgeLGThinQdata:  {"deviceId":"0776fc24-e9de-1726-82d2-44cb8be1cfbe","deviceType":201,"modelName":"FH6G1BAPK2_WW_SPI","subModelNm":null,"sensorType":null,"alias":"WASCHMASCHINE","deviceCode":"LA02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"XXXXXX","timezoneCode":"Europe/Berlin","timezoneCodeAlias":"Europe/Berlin","sdsGuide":"{\"deviceCode\":\"LA02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"990653","sleep":null,"deviceState":"D","rmsClientId":null,"regDtUtc":"20210430095037000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"washerDryer":{"myPattern2Detergent":"DETERGENT_OFF","addedDT":8,"dnnChangeSoilWash":"NO_SOILWASH","initialTimeMinute":0,"myPattern3CreaseCare":"CREASECARE_OFF","dnnWashBit":"DNNWASHBIT_OFF","myPattern3StainCare":"BLOOD","myPattern2CourseGplusBest":"AUTOWASH_CS","fotaProgress":0,"myPattern2SteamSoftener":"STEAMSOFTENER_OFF","preWash":"PREWASH_OFF","miniState":"NOT_DEFINE_VALUE value:0","myPattern3Proofing":"PROOFING_OFF","state":"POWEROFF","myPattern2Spin":"SPIN_1200","miniChildLock":"MINI_CHILDLOCK_OFF","FOTADownloadProgress":0,"miniCourseSpendWater":0,"detergentRemaining":"DETERGENT_REMAINING_YES","myPattern2DryLevel":"DRYLEVEL_NORMAL","courseMiniGplusBest":"NOT_SELECTED","myPattern3Rinse":"RINSE_NORMAL","currentTimeMinute":11,"courseSpendDetergent":0,"myPattern1GplusBestWash":"GPLUS_BEST_WASH_NORMAL","medicRinse":"MEDICRINSE_OFF","softenerRemaining":"SOFTENER_REMAING_NO","turboWash":"TURBOWASH_OFF","dnnSpinBit":"DNNSPINBIT_OFF","remainTimeMinute":0,"miniPreState":"NOT_DEFINE_VALUE value:0","miniCourseType":"COURSE_TYPE_COURSE","myPattern2Steam":"STEAM_OFF","childLock":"CHILDLOCK_OFF","myPattern3Temp":"TEMP_40","myPattern1Detergent":"DETERGENT_OFF","dnnChangeRinse":"NO_RINSE","standby":"STANDBY_OFF","autoWashStainLevel":3,"myPattern2InitialBit":"INITIAL_BIT_OFF","FOTAState":"NORMAL","myPattern1MedicRinse":"MEDICRINSE_OFF","myPattern3Steam":"STEAM_OFF","myPattern3PreWash":"PREWASH_OFF","creaseCare":"CREASECARE_OFF","myPattern3SteamSoftener":"STEAMSOFTENER_OFF","myPattern1CreaseCare":"CREASECARE_OFF","myPattern1SteamSoftener":"STEAMSOFTENER_OFF","smartCourseMainGplusBest":"NOT_SELECTED","myPattern3Softener":"SOFTENER_OFF","myPattern1Temp":"TEMP_40","miniTCLCount":0,"myPattern3DryLevel":"DRYLEVEL_NORMAL","downloadSlot6":"REFRESH","miniError":"ERROR_NO","detergentBox":"DETERGENT_BOX_OFF","courseMainGplusBest":"AUTOWASH_CS","downloadSlot1":"TUB_CLEAN","downloadSlot3":"SPIN","myPattern3SoilWash":"SOILWASH_HEAVY","downloadSlot2":"RINSE+SPIN","downloadSlot5":"DRAIN","downloadSlot4":"STEAM_CARE","spin":"SPIN_1200","courseDownloadAvailable":"CAN_DOWNLOAD","myPattern3HitCount":5,"myPattern2Rinse":"RINSE_NORMAL","myPattern2Softener":"SOFTENER_OFF","courseType":"COURSE_TYPE_MYPATTERN","myPattern1Proofing":"PROOFING_OFF","preState":"END","myPattern3Spin":"SPIN_1200","totalRinseCount":0,"currentTimeHour":20,"myPattern2MedicRinse":"MEDICRINSE_OFF","detergent":"DETERGENT_ON","dnnReady":"DNNREADY_OFF","courseSpendSoftener":0,"myPattern2TurboWash":"TURBOWASH_OFF","myPattern3InitialBit":"INITIAL_BIT_OFF","gplusBestWash":"GPLUS_BEST_WASH_NORMAL","miniRemainTimeMinute":0,"myPattern3GplusBestWash":"GPLUS_BEST_WASH_NORMAL","stainCare":"BLOOD","dnnBit":"DNNBIT_OFF","myPattern2GplusBestWash":"GPLUS_BEST_WASH_NORMAL","myPattern2Temp":"TEMP_40","steamSoftener":"STEAMSOFTENER_OFF","remoteStart":"REMOTE_START_OFF","myPattern2SoilWash":"SOILWASH_NORMAL","myPattern1TurboWash":"TURBOWASH_OFF","myPattern2HitCount":11,"myPattern1StainCare":"BLOOD","courseSpendWater":2,"miniCourseSpendPower":0,"initialBit":"INITIAL_BIT_ON","myPattern1Softener":"SOFTENER_OFF","myPattern1CourseGplusBest":"COTTON_CS","miniExtraRinse":"MINI_EXTRARINSE_0","miniPairing":"MINI_PAIRING_OFF","miniSpin":"SPIN_OFF","courseSpendPower":3,"error":"ERROR_NO","isMainComplete":"MAIN_NO","myPattern1Rinse":"RINSE_NORMAL","dryLevel":"DRYLEVEL_NORMAL","dnnChangeSpin":"NOT_SELECTED","myPattern1PreWash":"PREWASH_OFF","myPattern3Detergent":"DETERGENT_OFF","myPattern2PreWash":"PREWASH_OFF","myPattern2StainCare":"BLOOD","steam":"STEAM_OFF","softener":"SOFTENER_ON","isFOTAEnable":"DISABLE","myPattern2Proofing":"PROOFING_OFF","proofing":"PROOFING_OFF","rinse":"RINSE_NORMAL","myPattern1Steam":"STEAM_OFF","temp":"TEMP_40","myPattern1HitCount":13,"reserveTimeMinute":0,"myPattern1DryLevel":"DRYLEVEL_NORMAL","myPattern3CourseGplusBest":"COTTON_CS","miniRemoteStart":"REMOTE_START_OFF","myPattern2CreaseCare":"CREASECARE_OFF","TCLCount":14,"miniInitialBit":"MINI_INITIAL_BIT_OFF","myPattern1InitialBit":"INITIAL_BIT_OFF","myPattern1Spin":"SPIN_1200","standbySupport":"STANDBY_SUPPORT_NO","myPattern3TurboWash":"TURBOWASH_OFF","miniSoftenerRemaining":"MINI_SOFTENER_REMAING_NO","myPattern3MedicRinse":"MEDICRINSE_OFF","dnnAppliedProduct":"DNNAppliedProduct_NO","myPattern1SoilWash":"SOILWASH_NORMAL","miniInitialTimeMinute":0,"soilWash":"SOILWASH_NORMAL"},"mid":29429938,"online":false,"static":{"deviceType":"201","countryCode":"DE"},"meta":{"allDeviceInfoUpdate":false,"messageId":"reKKMsVbS5OVOO7b5j2jjA"},"timestamp":1625681194668},"manufacture":null,"online":false,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.84","modelJsonUri":"https://objectcontent.lgthinq.com/def50ae5-ab04-4491-933c-4e76387cf53e?hdnts=exp=1684465243~hmac=860d74c239f15c22b22e281a93b15e1a520658394631511141b11ab5bc9d4337","appModuleVer":"3.58","appModuleUri":"https://objectcontent.lgthinq.com/f308c27b-dceb-4484-b0c5-e9bdd4e49cae?hdnts=exp=1688009019~hmac=ab23ed75861eedf372062e104e7ba216716b168559a8febff9b059943c0d3ab6","appRestartYn":"Y","appModuleSize":"9833369","langPackProductTypeVer":"81.2","langPackProductTypeUri":"https://objectcontent.lgthinq.com/fdd6b1cc-eb94-4d5f-a174-4d77b805ab97?hdnts=exp=1687574778~hmac=c59d7af2e520517b956de00232c79325c4fd61034d154bd30d23c3c942fa7f92","langPackModelVer":"5.4","langPackModelUri":"https://objectcontent.lgthinq.com/8af076a7-2094-42c9-9d12-1ea101b43e73?hdnts=exp=1663070447~hmac=2df2e841d431866c911544b29f23bea749be0bc78bf947748657120f3784adec","roomId":"161355882211485249","fwInfoList":[{"checksum":"00000518","partNumber":"FH6G1BAPK2_WW_SPI","order":3},{"checksum":"0000E964","partNumber":"SAA38300911","order":2},{"checksum":"00001E4B","partNumber":"SAA38301002","order":1}],"modemInfo":{"modelName":"FH6G1BAPK2_WW_SPI","appVersion":"clip_spi_v1.9.049","modemType":"RTK_RTL8711am_SPI","ruleEngine":"n"},"existsEntryPopup":"N","fwVer":null,"modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:FL-S:24-U:600-P:GPLUS_BEST"}
8.7.2021, 06:46:46LG ThinQ BridgeLGThinQAdding new accessory: WASCHMASCHINE
8.7.2021, 06:46:46LG ThinQ BridgeLGThinQStart polling device data.

**Comment by nVuln** [comment]
I already published version `0.2.1-5.test-1` for your testing, please try

**Comment by Christian-CFP** [comment]
I will and give feedback.

**Comment by Christian-CFP** [comment]
I dont see this version

**Comment by Christian-CFP** [comment]
Make it visible in the Release section (as beta maybe)

**Comment by Christian-CFP** [comment]
HOOBS runs a little different now in V4.
If it is visible in the Release Section I can install in via HOOBS directly.
And now it's a perfect time for testing because my washer is still going.

**Comment by nVuln** [comment]
I already released `v0.2.15`

**Comment by Christian-CFP** [comment]
Error MSG disappeared and remaining Time is correct! THX.

In addition to an issue: It will be better if the "washer finished" button will be a sensor that takes care of.

**Comment by nVuln** [comment]
> Error MSG disappeared and remaining Time is correct! THX.
> 
> In addition to an issue: It will be better if the "washer finished" button will be a sensor that takes care of.

I'm still thinking about it, at this time we have washer door lock status, washer is done when door unlocked (this correct for me and some people), you can use this

**Comment by Christian-CFP** [comment]
hm...
I think that these are two different options.

Sensor for "Washer Program Finished". So it pops up in HK when washer has finished its program.

Door Lock Status: How Can I enable this because I cant see anything (HK does show shi*) but even in the EVE App I cant see a Door Lock function.

**Comment by nVuln** [comment]
> hm...
> I think that these are two different options.
> 
> Sensor for "Washer Program Finished". So it pops up in HK when washer has finished its program.
> 
> Door Lock Status: How Can I enable this because I cant see anything (HK does show shi*) but even in the EVE App I cant see a Door Lock function.

oop, your washer do not provide door lock status in device data, so door lock status is not enabled
at this time we cannot make a "custom sensor" to push notification "washer has finished" 😢

I'm thinking about make a fake motion sensor to simulate "washer finished" event, maybe in future update

**Comment by Christian-CFP** [comment]
Only for information.
My washer (LG LSWD100) has a door lock BUT the door opens only after washer is finished and you push the on/off button ;)
So the "fake" sensor musst be watching the actual program process not a door opening.
And btw. you have to adjust the remaining timer. Because my washer adjust the timer on the fly your timer hast to check the actual remaining time more often. When I reboot the timer get the actual remaining time but when the washer decides to cut of e.g. 10min because the laundry isn't that dirty your timer stays on the old one.

**Comment by nVuln** [comment]
nop, fake button pressed when stop time less than current time
so if your device not support door lock status, it doesn't matter

for remaining time, homekit need `time in second` and LG only provide `time in minute`, if I adjust time every minute, it's not running smooth
let see if I can handle it

**Comment by Christian-CFP** [comment]
Will take a look at the time if laudry lets me doing so ;)
Keep you updated!

**Comment by Christian-CFP** [comment]
Time is adjusting with the new version. Thx.
Now Im waiting for the sensor ;)
