### ISSUE TITLE
AC - How to disable buttons

### ISSUE THREAD

**Issue by joaolucasd** [nVuln/homebridge-lg-thinq#254]
How can I remove the 3 buttons that comes automatically on the device? I only want the temperature, fan and led control
+ question. How can I change the led light to a switch?

Thank you and I really appreciate for the great plugin.

**Comment by nVuln** [comment]
sorry I can't help, you can fork this repo and customize whatever you want
I don't give any option to remove "supported feature" via plugin setting, it's just make people confused

**Comment by joaolucasd** [comment]
Understandable! Thank you for you work! I use it all the time
