### ISSUE TITLE
LG Dryer DLEX5500V

### ISSUE THREAD

**Issue by mosherc** [nVuln/homebridge-lg-thinq#259]
**Which device do you want to add? Please describe:**

I bought a new front load washer and dryer set, and somehow only the washer is showing up in home bridge. I have both connected to the LG Thinq app. It is the LG Dryer DLEX5500V

**Describe the solution you'd like:**

I would like to be able to see this device in home bridge like my previous dryer.

**Device Data:**

10/27/2023, 10:52:44 PMHOOBSLGThinQSuccessfully connected to the ThinQ API.
10/27/2023, 10:52:46 PMHOOBSLGThinQ[Refrigerator] Setting up device!
10/27/2023, 10:52:46 PMHOOBSLGThinQAdding new accessory: 6c47d100-652d-1b7d-8d48-acf108806f2f: Refrigerator (REFRIGERATOR 2REF12EICD__2)
10/27/2023, 10:52:46 PMHOOBSLGThinQ[Washer] Setting up device!
10/27/2023, 10:52:46 PMHOOBSLGThinQAdding new accessory: 7e1275c8-8d35-16c8-995c-b8165fbf3014: Washer (WASHER FAFXU22027)
10/27/2023, 10:52:46 PMHOOBSLGThinQ[Dishwasher] Setting up device!
10/27/2023, 10:52:46 PMHOOBSLGThinQAdding new accessory: af904a66-7db8-1f3e-a03d-4cbce9807246: Dishwasher (DISHWASHER D3210)
10/27/2023, 10:52:46 PMHOOBSERROR[Dishwasher@Dishwasher Door@Battery Level] Characteristic not in required or optional characteristic section for service ContactSensor. Adding anyway.
10/27/2023, 10:52:46 PMHOOBSLGThinQ[Oven] Setting up device!
10/27/2023, 10:52:46 PMHOOBSLGThinQAdding new accessory: efc1ac9a-60a9-14e8-a579-4cbce99f40b3: Oven (OVEN WLD3653SP)
10/27/2023, 10:52:46 PMHOOBSLGThinQERRORCannot read properties of undefined (reading 'includes')

**Comment by nVuln** [comment]
you need go to plugin setting and add new device to the list
please share your plugin config (hide private information)

**Comment by mosherc** [comment]
Why does it not work automatically though? The instructions say
> `devices` List devices you want add to homebridge, leave it empty if you want add all devices

**Comment by nVuln** [comment]
> Why does it not work automatically though? The instructions say

yup, that why I asked your plugin config, to see if it's already fixed or dynamic

> I have also tried it using the token method and I also don't get the dryer that way.

did you linked your Dryer to LG account? can you screenshot your LG ThinQ mobile app?
also, please turn on homebridge debug mode and upload more log, let see what happened
