### ISSUE TITLE
Dishwasher added as TV

### ISSUE THREAD

**Issue by malwcal** [nVuln/homebridge-lg-thinq#261]
**Describe The Bug:**

Recently my dishwasher had a change of mainboard so I needed to re-add it to my LG ThinQ account.

To get it back into the plugin I changed the Device ID and restarted homebridge.  The log file said I need to add it manually, and when I did it decided to add it to my home as a TV?

**To Reproduce:**

I haven't tried to re-add this to see if it happens again.

**Expected behavior:**

I don't expect a dishwasher to appear as a TV in my home.

**Logs:**

```
Show the Homebridge logs here (make sure homebridge DEBUG mode is turned `on`), remove any sensitive information.
```

**Plugin Config:**

```
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

<img width="173" alt="image" src="https://github.com/nVuln/homebridge-lg-thinq/assets/1244623/f69e0020-3617-4979-a53c-2e5bcd26ba73">

**Environment:**

* **Plugin Version**:  v1.6.1
* **Homebridge Version**:   v1.6.1
* **Node.js Version**:  v20.5.1
* **NPM Version**:   10.2.1
* **Operating System**: 
Raspbian 11.8

**Comment by WhyElEss** [comment]
I have the same thing.

Once, removing the dishwasher from Apple Home, doing Remove Single Cached Accessory in the Homebridge settings, and then rebooting all hubs helped. 

Unfortunately, it only worked once. The dishwasher is now permanently detected in HomeKit as a TV after I replaced the Homebridge (I bought a new Raspberry Pi) and installed the plugin, and nothing else helps to fix it.

**Comment by nVuln** [comment]
at this time, no real Dishwasher supported in apple homekit, so we need simulate it as an other accessories

**Comment by malwcal** [comment]
Ok, that makes sense. I was surprised because before I had to re-add my dishwasher it didn’t appear as a TV. Also I couldn’t find reference to this fact in the documentation.But it’s all good: I like the improved reporting I now see in the home app. 👍🏻Malcolm CaldwellOn 5 Nov 2023, at 02:03, nVuln ***@***.***> wrote:﻿
at this time, no real Dishwasher supported in apple homekit, so we need simulate it as an other accessories

**Comment by nVuln** [comment]
> Ok, that makes sense. I was surprised because before I had to re-add my dishwasher it didn’t appear as a TV. Also I couldn’t find reference to this fact in the documentation.But it’s all good: I like the improved reporting I now see in the home app. 👍🏻Malcolm CaldwellOn 5 Nov 2023, at 02:03, nVuln ***@***.***> wrote:﻿ at this time, no real Dishwasher supported in apple homekit, so we need simulate it as an other accessories —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

yup, in previous version, dishwasher displayed as valve, but since ios 16, water valve no longer displayed as a tile on home app, make a lot of trouble

**Comment by malwcal** [comment]
Just noticed this is still open. It can be closed as a won't fix - since this is by design.
