### ISSUE TITLE
1.6.x fails to write accessories cache in HOOBS 4.3.0

### ISSUE THREAD

**Issue by claudiomorabito** [nVuln/homebridge-lg-thinq#265]
**Describe The Bug:**
Upgrading plugin to 1.6.0, 1.6.1, 1.6.2 makes the LG Thinq Washer disappear from the Hoobs Accessory Cache and, consequently, also from homekit.
The accessory DOES SHOW in the HOOBS accessory list.
Installing the 1.5.4 version FIXES the issue.
So it does not seem to be an hoobs issue but a 1.6.x  related issue.

**To Reproduce:**
Upgrade the plugin in Hoobs to 1.6.2. Or to 1.6.1 as well.

**Expected behavior:**
After configuring the plugin ,we expect that the discovered accessories appear in the Hoobs accessories cache, so that pairing the bridge to HomeKit makes them appear in the Home app too.

**Logs:**
No issues in the HB logs.

27/11/2023, 12:31:33Lg Thinq Bridge starting
27/11/2023, 12:31:42Lg Thinq BridgeLoaded plugin 'homebridge-lg-thinq'
27/11/2023, 12:31:43Lg Thinq BridgeLoading 1 platforms...
27/11/2023, 12:31:43Lg Thinq BridgeBridge is running on port 51856.
27/11/2023, 12:31:49Lg Thinq BridgeLGThinQSuccessfully connected to the ThinQ API.
27/11/2023, 12:31:50Lg Thinq BridgeLGThinQ[Lavatrice] Setting up device!
27/11/2023, 12:31:50Lg Thinq BridgeLGThinQAdding new accessory: 6861b70a-6007-1659-b159-4cbce9dfe236: Lavatrice (WASHER F_V7_F___W.B_2QEUK)
27/11/2023, 12:31:50Lg Thinq BridgeLGThinQStart MQTT listener for thinq2 device
27/11/2023, 12:31:50Lg Thinq BridgeLavatrice C166 is running on port 38093.
27/11/2023, 12:31:52Lg Thinq BridgeLGThinQSuccessfully connected to the MQTT server.

**Plugin Config:**
{
    "platform": "LGThinQ",
    "country": "IT",
    "language": "it-IT",
    "refresh_interval": 60,
    "auth_mode": "account",
    "username": "****@live.com",
    "password": "*******",
    "thinq1": true
}

The same configuration DOES WORK with 1.5.4 version of the plugin, so it does not seem to be a configuration related issue.

**Environment:**

* **Plugin Version**: 1.6.2
* **Homebridge Version**: Hoobs 4.3.0, HomeBridge 1.6.0
* **Node.js Version**: 16.20.2
* **NPM Version**: 8.19.4
* **Operating System**: Hoobs

**Comment by Guillaumichaud** [comment]
@jgstroud Same here.

**Comment by jgstroud** [comment]
I upgraded to 1.7.0 today and I don't see this issue anymore.

**Comment by Guillaumichaud** [comment]
> I upgraded to 1.7.0 today and I don't see this issue anymore.

Same here, it now works! :)
