### ISSUE TITLE
Setup Codes to install on Home??

### ISSUE THREAD

**Issue by pereiraj52** [nVuln/homebridge-lg-thinq#269]
Installed and paired child bridge to Apple Home. The devices (Fridge and Oven) and not automatically added. Instead when I go to add accessories/more options, I can see both.
When I try to add one I am told it is uncertified and when I am given the option to add anyway it ask for a homelkit setup code. 
I am not finding any reference to this or seeing a work around.

**Comment by nVuln** [comment]
check homebridge log, you can see it there
