### ISSUE TITLE
What are the correct login data

### ISSUE THREAD

**Issue by pc-bastler** [nVuln/homebridge-lg-thinq#27]
**Describe Your Problem:**

I am trying to use the plugin. I have to state my LG-username and the corresponding password.
For my configuration I used my Google-Account ("Log In with Google") to log in the LG-ThinQ app.

What do I have to configure in the config.json?

**Comment by nVuln** [comment]
at this time this plugin only support login by LG account
I'm currently working to support thirdparty login (google, facebook), for now, you can register new LG account (by username/password) and re-link your device, it's must easier

**Comment by nVuln** [comment]
btw, I already published `v1.0.0-test.1`, you can try this version to login with your Google in setting page

**Comment by pc-bastler** [comment]
Hi,

I already followed your suggestion and opened a new account with own login.
I had to see that my refrigerator seems to be one with the old API... now I use the WideQ-Addin which works perfect for me.
