### ISSUE TITLE
Please add support for LG televisions

### ISSUE THREAD

**Issue by RenzAchterberg** [nVuln/homebridge-lg-thinq#276]
**Which device do you want to add? Please describe:**
Logging returns: [LGThinQ] No ThinQ devices in your account.
I have 2 televisions added in ThinQ. Could you please add support for LG televisions?
Specifically I have the following two models:
LG OLED65C8PLA
LG UN74006LB

**Describe the solution you'd like:**
Support for these televisions. Controls for on/off, screen off, volume, mute, input selection, screensaver on, switches for launching apps.

**Device Data:**
None.

**Comment by nVuln** [comment]
tv not using thinq api so it's not covered by this plugin, you can looking for homebridge webos plugin
