### ISSUE TITLE
Sensor Automation Fails in HomeKit with LG Window AC (LW1217ERSM1)

### ISSUE THREAD

**Issue by JasonGoldenDDT** [nVuln/homebridge-lg-thinq#284]
**Describe The Bug:**
Air Condition Status Sensor (On/Off) falls out of sync with actual device status.  

I use the "sensor" to trigger other devices to turn on/off with the AC.   It's necessary for my setup.   I'm having issues with the sensor falling out of sync with the window ac, the sensor reports "off" when the ac is actually "on."  

The window AC appears OFF in HOMEKIT while remaining on. 

**To Reproduce:**
- Create a sensor trigger automation that turns off a light or fan when the AC turns on or off. 
- Create a temperature trigger that turns the AC on or off based on temperature threshold.  I have one set for 73 degrees, turning the AC off. Another set for 75 degrees, turning the AC on. 

**Expected behavior:**
I need the AC to respond and report its status consistently to avoid the AC running longer than it needs  to maintain the temperature. 

I have a UV light and Boost fan turn on and off with the AC.  If the sensor does not reflect the AC status correctly these things turn off/on at the wrong time.  The plugin will erroneously cycle these devices.   

**Logs:**
The plugin isn't showing log data when viewed via the plugin log option. 

<img width="523" alt="Screenshot 2024-03-26 at 6 46 35 AM" src="https://github.com/nVuln/homebridge-lg-thinq/assets/107149125/c07d3392-9bc9-473d-a54e-35318fe41526">

Manual Power Cycle log: 
[homebridge.log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/14763175/homebridge.log.txt)

This appears in the main log view in HomeKit:

[3/26/2024, 6:46:17 AM] [LGThinQ] [request] post https://aic-service.lgthinq.com:46030/v1/service/devices/c84cdce3-8a5a-12df-a0ba-b8165ff21cd8/control-sync
[3/26/2024, 6:46:17 AM] [LGThinQ] ThinQ Device Received the Command
[3/26/2024, 6:46:17 AM] [LGThinQ] [request] get https://aic-service.lgthinq.com:46030/v1/service/homes/REDACTED
[3/26/2024, 6:46:17 AM] [LGThinQ] [Air Conditioner] Received snapshot:  {"airState.windStrength":6,"airState.bellSound.control":1,"fwUpgradeInfo":{"upgSched":{"upgUtc":"0","cmd":"none"}},"static":{"deviceType":"401","countryCode":"US"},"airState.tempState.current":18.5,"airState.diagCode":0,"airState.lightingState.displayControl":1,"airState.wDir.hStep":0,"mid":88544966,"airState.energy.onCurrent":0,"airState.reservation.sleepTime":0,"airState.quality.sensorMon":0,"airState.tempState.target":16,"airState.DR.northAmerica":0,"airState.operation":0,"airState.reservation.targetTimeToStart":0,"meta":{"allDeviceInfoUpdate":false,"messageId":"gC2oQtlRQ4GpkspXA_XouQ"},"online":true,"airState.opMode":0,"airState.reservation.targetTimeToStop":0,"airState.filterMngStates.maxTime":250,"airState.filterMngStates.useTime":224,"timestamp":1711471059169}

**Plugin Config:**
        {
            "country": "US",
            "language": "en-US",
            "auth_mode": "token",
            "refresh_token": REDACTED,
            "username": REDACTED,
            "password": REDACTED,
            "devices": [
                {
                    "id": REDACTED,
                    "name": "Air Conditioner",
                    "type": "AC",
                    "serial_number": REDACTED,
                    "ac_mode": "COOLING",
                    "ac_fan_control": false,
                    "ac_temperature_unit": "F"
                }
            ],
            "thinq1": false,
            "refresh_interval": 30,
            "platform": "LGThinQ"
        }

**Screenshots:**
![Screenshot 2024-03-26 at 6 51 22 AM](https://github.com/nVuln/homebridge-lg-thinq/assets/107149125/340a88c6-cf87-458f-87d7-64c13db262c3)

**Environment:**

* **Plugin Version**: 1.8.1
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 20.11.1
* **NPM Version**: 10.2.4
* **Operating System**: Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by nVuln** [comment]
in your log, `"airState.operation":0` mean AC is off, matched your screenshot
can you try to collect some debug log white Homekit showing off and AC still on?

**Comment by JasonGoldenDDT** [comment]
Sure, I'll have more data tomorrow. I have debug logging turned on.

**Comment by nVuln** [comment]
I also publish test version `v1.8.2-test.4`, please pull and test it

**Comment by JasonGoldenDDT** [comment]
Attached the log from last night.   Around 2:11 am local time in the log I found the AC off, HomeKit reported the AC as ON. 

[homebridge.log-2.txt](https://github.com/nVuln/homebridge-lg-thinq/files/14776698/homebridge.log-2.txt)

**Comment by nVuln** [comment]
this is log around 2:11
```
[3/27/2024, 2:11:03 AM] [LGThinQ] [c84cdce3-8a5a-12df-a0ba-b8165ff21cd8] control - Operation -  basicCtrl: {"dataKey":"airState.operation","dataValue":0}
[3/27/2024, 2:11:05 AM] [LGThinQ] ThinQ Device Received the Command
```

I can see homebridge sent turn off command, so strange if homekit still reported it as ON

and then 2:12, turn on command was sent

```
[3/27/2024, 2:12:31 AM] [LGThinQ] [c84cdce3-8a5a-12df-a0ba-b8165ff21cd8] control - Operation -  basicCtrl: {"dataKey":"airState.operation","dataValue":1}
[3/27/2024, 2:12:31 AM] [LGThinQ] ThinQ Device Received the Command
```

is this correct?

**Comment by JasonGoldenDDT** [comment]
I have noticed a delay in homekit's status.  

Here is what I see at 2:10 & 2:11 am.



![image](https://github.com/nVuln/homebridge-lg-thinq/assets/107149125/f8b82f62-7c3b-42cc-8845-94e73fda36fc)

**Comment by nVuln** [comment]
in screenshot, current temperature at 74 degrees, it should be turn on?

**Comment by JasonGoldenDDT** [comment]
I set the temp to 60 and use a remote Philips motion sensor with a temp sensor to trigger when to turn the ac on or off. 

Below 73 turns on, over 74 turns off.  The AC isn't in the room I'm cooling.  I divert the air to a bedroom separated by a sliding door.  


The AC should be off.  

Last night this worked 90% of the time.  Then gets stuck when the ac falls out of sync.

**Comment by nVuln** [comment]
seem it happened when we received multiple on/off command at a same time
for example: automation OFF triggered at 1:00 and ON at 1:01, AC receive OFF at 1:00 and totally OFF at 1:03 so it's out of sync in Home app
I just refactor and added some debug log to version `v1.8.2-test.5`, let see

**Comment by JasonGoldenDDT** [comment]
I'll install the new test build.   

Are you able to see if the command is triggered by the AC's onboard temperature sensor?  I suspect it may be reading a temp below 60 when it kicks on and then kicks off on its own. 

I think I need to move the AC temp sensor probe to avoid the AC turning off using its own temp sensor.

**Comment by JasonGoldenDDT** [comment]
Quick update, before stepping away for the weekend.  

I moved the AC's temp sensor away from the air intake and the system ran as expected overnight with automation triggering on/off correctly.   I think this resolved the glitch I was experiencing with the AC falling out of sync with HomeKit. 

Thank you again for taking a look at this issue.

**Comment by nVuln** [comment]
@JasonGoldenDDT good to hear that, if you have any other problem related this plugin, just open new issue
