### ISSUE TITLE
This plugin threw an error from the characteristic 'Heating Threshold Temperature': Characteristic Property 'minValue' must be a finite number, received "Infinity" (number).

### ISSUE THREAD

**Issue by etienne678** [nVuln/homebridge-lg-thinq#285]
**Describe The Bug:**

Since v1.8.2 i get a new error message 

**To Reproduce:**

Update to v.1.8.2. and look at the logs. Downgrade to v.1.8.1. and the error is gone.

**Expected behavior:**

no error log should appear

**Logs:**

```
This plugin threw an error from the characteristic 'Heating Threshold Temperature': Characteristic Property 'minValue' must be a finite number, received "Infinity" (number).
```

**Plugin Config:**

```
{
    "country": "xxx",
    "language": "xxx",
    "auth_mode": "account",
    "refresh_token": "xxx",
    "username": "xxx",
    "password": "xxx",
    "devices": [
        {
            "id": "xxx",
            "name": "xxx",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_temperature_unit": "C"
        },
        {
            "id": "xxx",
            "name": "xxx",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_temperature_unit": "C"
        },
        {
            "id": "xxx",
            "name": "xxx",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_temperature_unit": "C"
        },
        {
            "id": "xxx",
            "name": "xxx",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_temperature_unit": "C"
        },
        {
            "id": "xxx",
            "name": "xxx",
            "type": "AC",
            "ac_mode": "BOTH",
            "ac_temperature_unit": "C"
        }
    ],
    "thinq1": false,
    "refresh_interval": 60,
    "platform": "LGThinQ"
}
```

**Environment:**

* **Plugin Version**: v.1.8.2.
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.10.0 
* **NPM Version**: 10.2.3
* **Operating System**: Raspian

**Comment by nVuln** [comment]
Turn on homebridge debug mode and collect some device data, need to see your model spec

**Comment by Jamyz** [comment]
I have same problems but i dont want insert all log here.
But if for AC RAC_056905.
You need more ?

**Comment by Jamyz** [comment]
"modelName":"RAC_056905_WW"

**Comment by etienne678** [comment]
> Turn on homebridge debug mode and collect some device data, need to see your model spec

The model i have running is AC RAC_056905

**Comment by Jamyz** [comment]
I dont no why but come back alone after few days off...

**Comment by Jamyz** [comment]
@nVuln I rename the file file.zip
[file.zip](https://github.com/nVuln/homebridge-lg-thinq/files/14852985/file.zip)

**Comment by nVuln** [comment]
I published test version `1.8.3-test.1` to fix this issue, please help me test it

**Comment by nVuln** [comment]
`1.8.3-test.2` is good now, just try it

**Comment by Jamyz** [comment]
@nVuln i dont have errors on logs. But all device as gone from app house "ios".
And i dont see devices on logs.
`[4/3/2024, 5:38:21 PM] [homebridge-lg-thinq] [request] get https://es.lgeapi.com/users/profile
[4/3/2024, 5:38:21 PM] [homebridge-lg-thinq] Successfully connected to the ThinQ API.
[4/3/2024, 5:38:21 PM] [homebridge-lg-thinq] [request] get https://eic-service.lgthinq.com:46030/v1/service/homes
[4/3/2024, 5:38:21 PM] [homebridge-lg-thinq] Device [Ar Quarto]:  SOMETHINGXXXXX: Ar Quarto (AC RAC_056905)
[4/3/2024, 5:38:21 PM] [homebridge-lg-thinq] Device skipped:  SOMETHINGXXXXX`
I come back in few hours

**Comment by nVuln** [comment]
sorry I pushed wrong version, tired day
try again at `1.8.3-test.3`

**Comment by etienne678** [comment]
> sorry I pushed wrong version, tired day try again at `1.8.3-test.3`

installed 1.8.3-test.3 and no error logs anymore. thank you!
