### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by Christian-CFP** [nVuln/homebridge-lg-thinq#30]
Hey,
so with version 1.0.0, if I by mistake click on the device in HK or Homebridge, the device enters the "not connected" state and wont get out of it until I restart the bridge.

My washer/dryer does not start with the "LG App" because when turned off - no WIFI. 
Even when I try to shut it off by clicking the device in HK or in Homebridge it does not work. (that does not work even bevor with ver. 0.2...)

(Lack of WASHER/DRYER in your device settings?)

**Comment by nVuln** [comment]
it's showing "not connected" even Washer still running ?

at this time Washer in home app only showing status and cannot control, I'll add washer on/off control in next release
but if "LG App" can't turn on/off, "home app" can't too

**Comment by Christian-CFP** [comment]
> it's showing "not connected" even Washer still running ?
> 
> 
> 
> at this time Washer in home app only showing status and cannot control, I'll add washer on/off control in next release
> 
> but if "LG App" can't turn on/off, "home app" can't too

I have to check if it still says not connected if I turn the washer on. 

You can turn the washer off in App but not on because when off WIFI is gone so no control anymore.

**Comment by Christian-CFP** [comment]
So if I click on the tile in HK when the washer is off, I get the not connected message. This stays for ever until I restart the homebridge and also after I turn the washer on.
