### ISSUE TITLE
Support for Window AC

### ISSUE THREAD

**Issue by bissen21** [nVuln/homebridge-lg-thinq#39]
**Which device do you want to add? Please describe:**
I would like to add support for window AC units.

**Describe the solution you'd like:**
I would like to control the thermostat and heating/cooling modes.

**Device Data:**
Device not supported: c3fc01e8-9330-16c1-93b2-1c392912c6a5: Attic (AC WIN_056905_WW)

**Comment by nVuln** [comment]
device data in debug logging is something like this `[LGThinQ] Found device:  {"deviceId":"xxxx-xxxx-xxx-xxxx", ......... }`, please upload it here
btw, did you try plugin `homebridge-lg-thinq-ac`?

**Comment by bissen21** [comment]
Found device:  
{
    "deviceId":"c3fc01e8-9330-16c1-93b2-1c392912c6a5",
    "deviceType":401,"modelName":"WIN_056905_WW",
    "subModelNm":null,
    "sensorType":null,
    "alias":"Attic",
    "deviceCode":"AI01",
    "networkType":"02",
    "tftYn":"N",
    "guideTypeYn":"Y",
    "guideType":"WIN_TYPE1",
    "pccModelYn":"N",
    "autoOrderYn":"N",
    "drServiceYn":"N",
    "ssid":"BillWiTheScienceFi",
    "timezoneCode":"America/Chicago",
    "timezoneCodeAlias":"USA/Chicago",
    "sdsGuide":"{\"deviceCode\":\"AI01\"}",
    "newRegYn":"N",
    "remoteControlType":"",
    "fareTarget":null,
    "area":"338222",
    "sleep":null,
    "deviceState":"E",
    "rmsClientId":null,
    "regDtUtc":"20210806022320000",
    "regIndex":0,
    "blackboxYn":"Y",
    "groupableYn":"Y",
    "controllableYn":"Y",
    "combinedProductYn":"N",
    "masterYn":"Y",
    "snapshot":{
        "airState.windStrength":6,
        "static":{"
            deviceType":"401",
            "countryCode":"US"},
    "airState.tempState.current":22,
    "airState.diagCode":0,"
    airState.wDir.hStep":0,
    "mid":21895549,
    "airState.reservation.sleepTime":0,
    "airState.quality.sensorMon":0,
    "airState.tempState.target":23,
    "airState.operation":1,
    "airState.reservation.targetTimeToStart":0,
    "meta":{
        "allDeviceInfoUpdate":false,
        "messageId":"YDVVnxLwQUutxTGt4tHuyg"
    },
    "online":true,
    "airState.opMode":8,
    "airState.reservation.targetTimeToStop":0,
    "airState.filterMngStates.maxTime":250,
    "airState.filterMngStates.useTime":205,
    "timestamp":1628377142651},
    "manufacture":null,"
    online":true,
    "platformType":"thinq2",
    "homeDeviceOrder":-1,
    "roomDeviceOrder":-1,
    "ownershipYn":"Y",
    "modelJsonVer":"10.38",
    "modelJsonUri":"https://objectcontent.lgthinq.com/19888a77-9997-4852-8c25-30bf1e5922bf?hdnts=exp=1691289620~hmac=ba2ca2f805e97ee6219e67c29b2ca24cc580a48a35d1892436220b62e692d250",
    "appModuleVer":"16.32",
    "appModuleUri":"https://objectcontent.lgthinq.com/6c1a78d3-0404-4712-a5bc-2bc3d9e072b8?hdnts=exp=1685169055~hmac=8b538678344ed708bd929b66403d075c761cc94be01589d82200ab3e93c3fa57",
    "appRestartYn":"Y",
    "appModuleSize":"13305760",
    "langPackProductTypeVer":"51.5",
    "langPackProductTypeUri":"https://objectcontent.lgthinq.com/55705346-01cf-4b6a-8b32-624b67736361?hdnts=exp=1689818864~hmac=4c0c81dd2d49bc21e32521b19dc9666a3c24f2b15fd4af96eda170bce9a00fe0",
    "langPackModelVer":null,
    "langPackModelUri":null,
    "roomId":"162822178926124896",
    "fwInfoList":[{
        "checksum":"00006210",
        "partNumber":"SAA37806210",
        "order":2},{
            "checksum":"00000BA9",
            "partNumber":"SAA36766232",
            "order":1
    }],
    "modemInfo":{
        "modelName":"WIN_056905_WW","
        appVersion":"clip_hna_v1.9.099",
        "modemType":"RTK_RTL8711am",
        "ruleEngine":"y"
    },
    "existsEntryPopup":"N",
    "fwVer":null,
    "modemVer":"clip_hna_v1.9.092",
    "subDeviceCount":0,
    "firebaseLogKey":"P:SD-T:C",
    "cardType":"Small",
    "cardControl":"Base"
}

**Comment by bissen21** [comment]
That one said it was only for portable AC units and was only tested with the single model. I'll give it a shot though and see if it works. This plug-in definitely seemed more promising from the readme, and I'm willing to contribute a bit if I can be any help.

**Comment by bissen21** [comment]
`homebridge-lg-thinq-ac `does appear to work

**Comment by nVuln** [comment]
I already published first testing version for AC `v1.1.0-ac.1`, help me test it and following up at #41
