### ISSUE TITLE
Longer or variable interval

### ISSUE THREAD

**Issue by hugoh** [nVuln/homebridge-lg-thinq#40]
Currently, polling interval is set to 5 seconds:

```ts
private readonly intervalTime = 5000; // 5 second
```

This generates quite a bit of traffic and seems overkill.

Any chance it can be either increased (I'm thinking that 60 seconds would be acceptable) or made configurable?

Thanks.

**Comment by nVuln** [comment]
refresh interval is configurable in `v1.0.4` and it's changed to 60s as default, thanks for your suggestion
