### ISSUE TITLE
add REFRIGERATOR

### ISSUE THREAD

**Issue by MobsX** [nVuln/homebridge-lg-thinq#43]
**Which device do you want to add? Please describe: REFRIGERATOR**

**Describe the solution you'd like:want to see temperature fridge and freezer. Include express cool, Express freeze, Eco friendly**

**LGThinQ] Found device:  {"deviceId":"09b19bb0-3598-11ea-ae9b-2c2bf91f58d0","deviceType":101,"modelName":"2REB1RUVB1___","subModelNm":null,"sensorType":null,"alias":"Холодильник","deviceCode":"KI0104","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Xiaomi_10EA","timezoneCode":"Europe/Moscow","timezoneCodeAlias":"Russia/Moscow","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"294021","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210530194431000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.3","modelJsonUri":"https://ruic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REB1RUVB1___&countryCode=WW&contentsId=JS0821011323662714&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"46.9","langPackProductTypeUri":"https://objectcontent.lgthinq.com/e35aae54-9a8a-4765-809b-fba67975cba0?hdnts=exp=1691050325~hmac=4c6b3e26a8597e690e82d54bb237039ddbbd165eae8ad15b97a19f8bcd328182","langPackModelVer":"","langPackModelUri":"","roomId":"162238349239194552","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.79","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFBF-M:2D-P:P_V+BF2","cardType":"Small","cardControl":"Base"} :

[LGThinQ] Device not connected:  09b19bb0-3598-11ea-ae9b-2c2bf91f58d0: Холодильник (REFRIGERATOR 2REB1RUVB1___)**

**Comment by MobsX** [comment]
**Which device do you want to add? Please describe:**


**Describe the solution you'd like:**


**Device Data:**

**Comment by nVuln** [comment]
I already added it on `v1.0.9`, but I don't have thinq1 device so I can't test it
please try and let me know if it's not working

**Comment by MobsX** [comment]
> I already added it on `v1.0.10`, but I don't have thinq1 device so I can't test it
> please try and let me know if it's not working

updated to v1.0.11 but did not appear in the refrigerator accessories.
Сообщение без thinq1: [12/08/2021, 09:01:28] [LGThinQ] Thinq1 device is skipped:  09b19bb0-3598-11ea-ae9b-2c2bf91f58d0: Холодильник (REFRIGERATOR 2REB1RUVB1___)
[12/08/2021, 09:01:28] [LGThinQ] START polling device data.

If I check thinq1: [LGThinQ] Found device:  {"deviceId":"09b19bb0-3598-11ea-ae9b-2c2bf91f58d0","deviceType":101,"modelName":"2REB1RUVB1___","subModelNm":null,"sensorType":null,"alias":"Холодильник","deviceCode":"KI0104","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"Xiaomi_10EA","timezoneCode":"Europe/Moscow","timezoneCodeAlias":"Russia/Moscow","sdsGuide":"{\"deviceCode\":\"KI01\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"294021","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210530194431000","regIndex":0,"blackboxYn":null,"groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","manufacture":null,"online":false,"platformType":"thinq1","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"2.3","modelJsonUri":"https://ruic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2REB1RUVB1___&countryCode=WW&contentsId=JS0821011323662714&authKey=thinq","appModuleVer":"303.20","appModuleUri":"https://objectcontent.lgthinq.com/564c4846-f80f-4865-9372-31160a1010ed?hdnts=exp=1684281366~hmac=a0802768ae20ee30aa6d9154e23878212b6f5a87aff505bb35aafd7d4d3f9561","appRestartYn":"Y","appModuleSize":"7337592","langPackProductTypeVer":"46.9","langPackProductTypeUri":"https://objectcontent.lgthinq.com/e35aae54-9a8a-4765-809b-fba67975cba0?hdnts=exp=1691050325~hmac=4c6b3e26a8597e690e82d54bb237039ddbbd165eae8ad15b97a19f8bcd328182","langPackModelVer":"","langPackModelUri":"","roomId":"162238349239194552","fwInfoList":null,"modemInfo":null,"existsEntryPopup":"N","fwVer":"QC_Modem_1.2.79","modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:RFBFBF-M:2D-P:P_V+BF2","cardType":"Small","cardControl":"Base"}
(node:11708) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at DeviceModel.decodeMonitorBinary (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:211:23)
    at DeviceModel.decodeMonitor (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/DeviceModel.ts:197:19)
    at Object.RefState [as default] (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/transforms/RefState.ts:10:38)
    at Function.transform (/usr/local/lib/node_modules/homebridge-lg-thinq/src/v1/helper.ts:36:40)
    at ThinQ.pollMonitor (/usr/local/lib/node_modules/homebridge-lg-thinq/src/lib/ThinQ.ts:132:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at LGThinQHomebridgePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:100:34)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lg-thinq/src/platform.ts:53:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nVuln** [comment]
is your refrigerator still work on LG ThinQ app ?
I saw `"online":false` in your device data, look like your device is not online

**Comment by MobsX** [comment]
> I saw `"online":false` in your device data, look like your device is not online

This is wrong. The refrigerator works in the standard application

**Comment by MobsX** [comment]
> can you share me your `refresh token`? it's better for me to debug it
> I don't have any thinq1 device right here, so I can't test anything
> if you ready to share, this is my email: [j@shopar.dev](mailto:j@shopar.dev)

sent

**Comment by nVuln** [comment]
> > can you share me your `refresh token`? it's better for me to debug it
> > I don't have any thinq1 device right here, so I can't test anything
> > if you ready to share, this is my email: [j@shopar.dev](mailto:j@shopar.dev)
> 
> sent

thank you so much, I already published `v1.0.12`, please try it, this is my screenshot, hope it correct
<img width="693" alt="Screen Shot 2021-08-12 at 2 27 05 PM" src="https://user-images.githubusercontent.com/54855446/129155809-af49f6c2-6ea7-44a5-8f26-82a27ded3d6a.png">

**Comment by MobsX** [comment]
Working! Thank you!

> 12 авг. 2021 г., в 10:28, nVuln ***@***.***> написал(а):
> 
> thank you so much, I already published v1.0.12, please try it, this is my screenshot, hope it correct
