### ISSUE TITLE
Washer Door „uknown status”

### ISSUE THREAD

**Issue by adamrzanek** [nVuln/homebridge-lg-thinq#53]
The Washer Door accessory is showing unknown status in home app. Notifications are working correctly. 

![B693542C-F22B-4560-AE69-25EE16BBEFB5](https://user-images.githubusercontent.com/65444919/129940642-989c4f3f-c143-4ebd-a154-167f92651393.png)

**Comment by adamrzanek** [comment]
When I’m reverting back to 1.0.04 then it’s ok

**Comment by nVuln** [comment]
Because your washer is disconnected, so I changed status to Unknown, not sure door locked or unlock at this state

**Comment by adamrzanek** [comment]
Hmm I think it’s strange. When the washer is off then it’s definitely unlock

**Comment by nVuln** [comment]
> Hmm I think it’s strange. When the washer is off then it’s definitely unlock
> […](#)
> On 18 Aug 2021, at 21:14, nVuln ***@***.***> wrote: ﻿ Because your washer is disconnected, so I changed status to Unknown, not sure door locked or unlock at this state — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

not sure if washer is really OFF, or maybe disconnected due internet issue 🥲
this status only show in first boot (reboot), when you start washer, it's will saved last state

**Comment by nVuln** [comment]
I just removed UNKNOWN state in latest version, please check

**Comment by adamrzanek** [comment]
Thanks I will test it tomorrow
