### ISSUE TITLE
Device locations get reset on Homebridge restart

### ISSUE THREAD

**Issue by navy5356** [nVuln/homebridge-lg-thinq#57]
Every time the HomeBridge is restarted, all my Thinq devices get reset and added as new devices, with all the room information lost. Furthermore, since adding my 2 Thinq ACs, on restarting, none of the ThinQ appliances show up and my other plugins become non-responsive. The only way to fix this that I have seen, is to remove the Homebridge from the Home app and add it again as a new accessory, upon which all the accessories are once again detected including the ThinQ ones from this plugin.

**Comment by nVuln** [comment]
update to `v1.1.1` and try again, I just re-enabled accessory cache
