### ISSUE TITLE
MQTT listener error? status code 400

### ISSUE THREAD

**Issue by Christian-CFP** [nVuln/homebridge-lg-thinq#78]
Hi, there is some error after the MQTT listener, See below:

12.9.2021, 07:41:27LG ThinQ BridgeInitializing HAP-NodeJS v0.9.4...
12.9.2021, 07:41:28LG ThinQ BridgeLoaded plugin 'homebridge-lg-thinq'
12.9.2021, 07:41:28LG ThinQ BridgeRegistering platform 'homebridge-lg-thinq.LGThinQ'
12.9.2021, 07:41:28LG ThinQ BridgeLoading 1 platforms...
12.9.2021, 07:41:28LG ThinQ BridgeLGThinQLoading accessory from cache: Waschmaschine
12.9.2021, 07:41:28LG ThinQ BridgeLGThinQExecuted didFinishLaunching callback
12.9.2021, 07:41:28LG ThinQ BridgePreparing Advertiser for 'LG ThinQ Bridge 8502' using bonjour-hap backend!
12.9.2021, 07:41:28LG ThinQ BridgeSetup URI 'X-HM://0023ISYWY4SL9'
12.9.2021, 07:41:28LG ThinQ BridgeStarting to advertise 'LG ThinQ Bridge 8502' using bonjour-hap backend!
12.9.2021, 07:41:28LG ThinQ BridgeBridge is running on port 52826.
12.9.2021, 07:41:33LG ThinQ BridgeLGThinQFound device:  {"deviceId":"0776fc24-e9de-1726-82d2-44cb8be1cfbe","deviceType":201,"modelName":"FH6G1BAPK2_WW_SPI","subModelNm":null,"sensorType":null,"alias":"Waschmaschine","deviceCode":"LA02","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE1","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"XXX","timezoneCode":"Europe/Berlin","timezoneCodeAlias":"Europe/Berlin","sdsGuide":"{\"deviceCode\":\"LA02\"}","newRegYn":"N","remoteControlType":"","fareTarget":null,"area":"990653","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20210430095037000","regIndex":0,"blackboxYn":"Y","groupableYn":"N","controllableYn":"N","combinedProductYn":"N","masterYn":"Y","snapshot":{"washerDryer":{"myPattern2Detergent":"DETERGENT_OFF","addedDT":0,"dnnChangeSoilWash":"NO_SOILWASH","initialTimeMinute":174,"myPattern3CreaseCare":"CREASECARE_OFF","dnnWashBit":"DNNWASHBIT_OFF","myPattern3StainCare":"BLOOD","myPattern2CourseGplusBest":"COTTON_CS","fotaProgress":0,"myPattern2SteamSoftener":"STEAMSOFTENER_OFF","preWash":"PREWASH_OFF","miniState":"NOT_DEFINE_VALUE value:0","myPattern3Proofing":"PROOFING_OFF","state":"RUNNING","myPattern2Spin":"SPIN_1200","miniChildLock":"MINI_CHILDLOCK_OFF","FOTADownloadProgress":0,"miniCourseSpendWater":0,"detergentRemaining":"DETERGENT_REMAINING_NO","myPattern2DryLevel":"DRYLEVEL_NORMAL","courseMiniGplusBest":"NOT_SELECTED","myPattern3Rinse":"RINSE_NORMAL","currentTimeMinute":51,"courseSpendDetergent":2,"myPattern1GplusBestWash":"GPLUS_BEST_WASH_NORMAL","medicRinse":"MEDICRINSE_OFF","softenerRemaining":"SOFTENER_REMAING_NO","turboWash":"TURBOWASH_ON","dnnSpinBit":"DNNSPINBIT_OFF","remainTimeMinute":161,"miniPreState":"NOT_DEFINE_VALUE value:0","miniCourseType":"COURSE_TYPE_COURSE","myPattern2Steam":"STEAM_OFF","childLock":"CHILDLOCK_OFF","myPattern3Temp":"TEMP_40","myPattern1Detergent":"DETERGENT_OFF","dnnChangeRinse":"NO_RINSE","standby":"STANDBY_OFF","autoWashStainLevel":0,"myPattern2InitialBit":"INITIAL_BIT_OFF","FOTAState":"NORMAL","myPattern1MedicRinse":"MEDICRINSE_OFF","myPattern3Steam":"STEAM_OFF","myPattern3PreWash":"PREWASH_OFF","creaseCare":"CREASECARE_OFF","myPattern3SteamSoftener":"STEAMSOFTENER_OFF","myPattern1CreaseCare":"CREASECARE_OFF","myPattern1SteamSoftener":"STEAMSOFTENER_OFF","smartCourseMainGplusBest":"NOT_SELECTED","myPattern3Softener":"SOFTENER_OFF","myPattern1Temp":"TEMP_40","miniTCLCount":0,"myPattern3DryLevel":"DRYLEVEL_NORMAL","downloadSlot6":"REFRESH","miniError":"ERROR_NO","detergentBox":"DETERGENT_BOX_OFF","courseMainGplusBest":"COTTON_CS","downloadSlot1":"TUB_CLEAN","downloadSlot3":"SPIN","myPattern3SoilWash":"SOILWASH_HEAVY","downloadSlot2":"RINSE+SPIN","downloadSlot5":"DRAIN","downloadSlot4":"STEAM_CARE","spin":"SPIN_1200","courseDownloadAvailable":"CAN_NOT_DOWNLOAD","myPattern3HitCount":10,"myPattern2Rinse":"RINSE_NORMAL","myPattern2Softener":"SOFTENER_OFF","courseType":"COURSE_TYPE_COURSE","myPattern1Proofing":"PROOFING_OFF","preState":"DISPENSING","myPattern3Spin":"SPIN_1200","totalRinseCount":2,"currentTimeHour":7,"myPattern2MedicRinse":"MEDICRINSE_OFF","detergent":"DETERGENT_ON","dnnReady":"DNNREADY_OFF","courseSpendSoftener":0,"myPattern2TurboWash":"TURBOWASH_OFF","myPattern3InitialBit":"INITIAL_BIT_OFF","gplusBestWash":"GPLUS_BEST_WASH_TURBOWASH","miniRemainTimeMinute":0,"myPattern3GplusBestWash":"GPLUS_BEST_WASH_NORMAL","stainCare":"BLOOD","dnnBit":"DNNBIT_OFF","myPattern2GplusBestWash":"GPLUS_BEST_WASH_NORMAL","myPattern2Temp":"TEMP_40","steamSoftener":"STEAMSOFTENER_OFF","remoteStart":"REMOTE_START_OFF","myPattern2SoilWash":"SOILWASH_NORMAL","myPattern1TurboWash":"TURBOWASH_OFF","myPattern2HitCount":20,"myPattern1StainCare":"BLOOD","courseSpendWater":1,"miniCourseSpendPower":0,"initialBit":"INITIAL_BIT_ON","myPattern1Softener":"SOFTENER_OFF","myPattern1CourseGplusBest":"AUTOWASH_CS","miniExtraRinse":"MINI_EXTRARINSE_0","miniPairing":"MINI_PAIRING_OFF","miniSpin":"SPIN_OFF","courseSpendPower":1,"error":"ERROR_NO","isMainComplete":"MAIN_NO","myPattern1Rinse":"RINSE_NORMAL","dryLevel":"DRYLEVEL_NORMAL","dnnChangeSpin":"NOT_SELECTED","myPattern1PreWash":"PREWASH_OFF","myPattern3Detergent":"DETERGENT_OFF","myPattern2PreWash":"PREWASH_OFF","myPattern2StainCare":"BLOOD","steam":"STEAM_OFF","softener":"SOFTENER_ON","isFOTAEnable":"DISABLE","myPattern2Proofing":"PROOFING_OFF","proofing":"PROOFING_OFF","rinse":"RINSE_NORMAL","myPattern1Steam":"STEAM_OFF","temp":"TEMP_40","myPattern1HitCount":22,"reserveTimeMinute":0,"myPattern1DryLevel":"DRYLEVEL_NORMAL","myPattern3CourseGplusBest":"COTTON_CS","miniRemoteStart":"REMOTE_START_OFF","myPattern2CreaseCare":"CREASECARE_OFF","TCLCount":48,"miniInitialBit":"MINI_INITIAL_BIT_OFF","myPattern1InitialBit":"INITIAL_BIT_OFF","myPattern1Spin":"SPIN_1200","standbySupport":"STANDBY_SUPPORT_NO","myPattern3TurboWash":"TURBOWASH_OFF","miniSoftenerRemaining":"MINI_SOFTENER_REMAING_NO","myPattern3MedicRinse":"MEDICRINSE_OFF","dnnAppliedProduct":"DNNAppliedProduct_NO","myPattern1SoilWash":"SOILWASH_NORMAL","miniInitialTimeMinute":0,"soilWash":"SOILWASH_NORMAL"},"mid":957092,"online":true,"static":{"deviceType":"201","countryCode":"DE"},"meta":{"allDeviceInfoUpdate":false,"messageId":"KUg3aqAeQICvroZgjVcqMQ"},"timestamp":1631425256632},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"1.84","modelJsonUri":"https://objectcontent.lgthinq.com/def50ae5-ab04-4491-933c-4e76387cf53e?hdnts=exp=1684465243~hmac=860d74c239f15c22b22e281a93b15e1a520658394631511141b11ab5bc9d4337","appModuleVer":"3.63","appModuleUri":"https://objectcontent.lgthinq.com/27342417-7989-4cd5-a248-9b204c437c3d?hdnts=exp=1690080696~hmac=57e58b829363251d0615a494886d685f1148c1f74649cb04d9fd7a19ebd3484b","appRestartYn":"Y","appModuleSize":"9896643","langPackProductTypeVer":"84.4","langPackProductTypeUri":"https://objectcontent.lgthinq.com/bf9fcaa2-dfa9-47c1-8212-91e8b63b8112?hdnts=exp=1694177582~hmac=0660640f89f63b21af5cc4d9227aa03eb236e172884a56ef4b8bd8fbb3ee8590","langPackModelVer":"5.4","langPackModelUri":"https://objectcontent.lgthinq.com/8af076a7-2094-42c9-9d12-1ea101b43e73?hdnts=exp=1663070447~hmac=2df2e841d431866c911544b29f23bea749be0bc78bf947748657120f3784adec","roomId":"161355882211485249","fwInfoList":[{"checksum":"00000518","partNumber":"FH6G1BAPK2_WW_SPI","order":3},{"checksum":"0000E964","partNumber":"SAA38300911","order":2},{"checksum":"00001E4B","partNumber":"SAA38301002","order":1}],"modemInfo":{"modelName":"FH6G1BAPK2_WW_SPI","appVersion":"clip_spi_v1.9.049","modemType":"RTK_RTL8711am_SPI","ruleEngine":"n"},"existsEntryPopup":"N","fwVer":null,"modemVer":null,"subDeviceCount":0,"firebaseLogKey":"T:FL-S:24-U:600-P:GPLUS_BEST","cardType":"Small","cardControl":"Base"}
12.9.2021, 07:41:33LG ThinQ BridgeLGThinQRestoring existing accessory from cache: Waschmaschine
12.9.2021, 07:41:33LG ThinQ BridgeLGThinQSTART MQTT listener for thinq2 device
12.9.2021, 07:41:33LG ThinQ BridgeWARNUNGunhandled rejection: Error: Request failed with status code 400

**Comment by nVuln** [comment]
you should downgrade to `v1.1.x` version and wait, I tested many many times before release and never got any problem like this in my end, just wait if someone get same issue and they can debug it

**Comment by nVuln** [comment]
can you try install v1.2.0-mqtt.1 and test ?

**Comment by Christian-CFP** [comment]
Its the same even with v1.2.0-mqtt.1

09:47:53LG ThinQ BridgeWARNUNGunhandled rejection: Error: Request failed with status code 400

**Comment by nVuln** [comment]
please try again `v1.2.0-mqtt.2`, I'm trying to investigate your problem
also please post your homebridge version and nodejs version

**Comment by Christian-CFP** [comment]
Nope:
12.9.2021, 10:34:00LG ThinQ Bridge WARNUNG unhandled rejection: Error: Request failed with status code 400

HB: 1.3.4
Node: 14.17.6

**Comment by nVuln** [comment]
please try `v1.2.0-mqtt.3`

**Comment by Christian-CFP** [comment]
YES! No more warning message:
14:04:05LG ThinQ Bridge LGThinQ START MQTT listener for thinq2 device

**Comment by Christian-CFP** [comment]
But now if the washer is off this happens:

19:49:31LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!

**Comment by nVuln** [comment]
> But now if the washer is off this happens:
> 
> 
> 
> 19:49:31LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!

How many disconnected error you got? Can you upload all debug log?

**Comment by Christian-CFP** [comment]
This is all I got in the debug:

12.9.2021, 19:49:31 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!
12.9.2021, 19:50:47 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!
12.9.2021, 19:52:35 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!
12.9.2021, 19:53:50 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!
12.9.2021, 19:55:38 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!
12.9.2021, 19:56:54 LG ThinQ BridgeLG ThinQ MQTT disconnected, retrying in 60 seconds!

**Comment by Christian-CFP** [comment]
If this helps more:
12.9.2021, 19:59:58LG ThinQ BridgeLGThinQSTART MQTT listener for thinq2 device
12.9.2021, 20:00:00LG ThinQ BridgeLGThinQmqtt connecting: ssl://a3phael99lf879-ats.iot.eu-west-1.amazonaws.com:8883
12.9.2021, 20:00:44LG ThinQ BridgeLGThinQMQTT disconnected, retrying in 60 seconds!
12.9.2021, 20:01:45LG ThinQ BridgeLGThinQmqtt connecting: ssl://a3phael99lf879-ats.iot.eu-west-1.amazonaws.com:8883
12.9.2021, 20:02:02LG ThinQ BridgeLGThinQMQTT disconnected, retrying in 60 seconds!

**Comment by Christian-CFP** [comment]
This is how it looks in my log:
![Bildschirmfoto 2021-09-12 um 20 04 47](https://user-images.githubusercontent.com/39855486/132998034-a71bd8f1-17d5-4edf-a8f2-4d9a57b5e952.jpg)

**Comment by nVuln** [comment]
please update `v1.2.2` and see if mqtt disconnect error is solved

**Comment by Christian-CFP** [comment]
So far so good. I'll keep you updated after the next washing. 👍🏻

**Comment by nVuln** [comment]
> So far so good. I'll keep you updated after the next washing. 👍🏻

I also fix washer trigger on that version, hope it's work better

**Comment by iFrez** [comment]
I got smae error v1.2.7

![83v9kw2TT9](https://user-images.githubusercontent.com/2266343/135862215-c052c242-d1a0-4325-9d30-56d72be3ebf3.png)

**Comment by nVuln** [comment]
> I got same error v1.2.7
> 
> ![83v9kw2TT9](https://user-images.githubusercontent.com/2266343/135862215-c052c242-d1a0-4325-9d30-56d72be3ebf3.png)

Did you got error on previous version ?
Where have you installed homebridge ?

**Comment by iFrez** [comment]
Yes, i got error on previous version of the plugin. I use it on Raspberry Pi Zero W. [#89](https://github.com/nVuln/homebridge-lg-thinq/issues/89)
