### ISSUE TITLE
Version 1.2.1 adds 1 hours to the washing program

### ISSUE THREAD

**Issue by frankebobdk** [nVuln/homebridge-lg-thinq#80]
Hi, 

After the newest update 1.21. every washing program gets 1 hour added to the countdown timer :-(  

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.17.6 
* **NPM Version**: 6.14.15
* **Operating System**: Raspbian

**Comment by nVuln** [comment]
turn on homebridge debug mode, and upload your debug log

**Comment by frankebobdk** [comment]
Sorry forgot to say that the error happen when the timer went under 1 hour. 
So it should have said 59 minutes and 59 second left, but instead changed it to 1 hour and 59 minutes and 59 seconds left. 
I don't have any "errors" in the log files and after I turned on debug it changed the result to the correct time. So maybe it's only a bug when the program is over 1 hour?

**Comment by nVuln** [comment]
> Sorry forgot to say that the error happen when the timer went under 1 hour. 
> 
> So it should have said 59 minutes and 59 second left, but instead changed it to 1 hour and 59 minutes and 59 seconds left. 
> 
> I don't have any "errors" in the log files and after I turned on debug it changed the result to the correct time. So maybe it's only a bug when the program is over 1 hour? 

I'm not sure about this, maybe delay on update device data, or maybe hour field of your device is different
Next time you run your washer, turn on debug mode to see device data, let me know if something wrong

**Comment by frankebobdk** [comment]
I spoke to soon - the timer keeps respawning the timer back to 2 minutes left. Even though the washer is done for at least 1 hour. 

Here is the debug data. 

[homebridge.log](https://github.com/nVuln/homebridge-lg-thinq/files/7149960/homebridge.log)

**Comment by nVuln** [comment]
> I spoke to soon - the timer keeps respawning the timer back to 2 minutes left. Even though the washer is done for at least 1 hour. 
> 
> 
> 
> Here is the debug data. 
> 
> 
> 
> [homebridge.log](https://github.com/nVuln/homebridge-lg-thinq/files/7149960/homebridge.log)
> 
> 

Too many disconnected error, is your network still normal?
In v1.2, I used mqtt protocol to get device data, maybe it's missed when remain hour changed

Sometime, it's got new data changed, almost disconnected after a few second
![image](https://user-images.githubusercontent.com/54855446/132996800-3b3513db-9c80-4872-a8cc-3d6e7ee02d8b.jpeg)

**Comment by frankebobdk** [comment]
My network is behaving normal - My washer is only 1,5 meter away from the acces point. Just downgraded to 1.1.5 and everything is worked again and is lightning fast. 
On this version, as soon as the washer is finished homekit sends a notification. Only nano seconds behind the LG ThinQ app.

I tried the 1.2.0 version, but it's the same as 1.2.1.

**Comment by nVuln** [comment]
I handled mqtt disconnected error on v1.2.2, can you help me update and try it?

**Comment by frankebobdk** [comment]
Of course- I'll update to 1.2.2 and keep you notified with the outcome next time we run the washer. 
Probably later today 😉

**Comment by frankebobdk** [comment]
Just a quick update - the mqtt disconnect error is gone with version 1.2.2 and the notifications are now working as it should :)

**Comment by nVuln** [comment]
> Just a quick update - the mqtt disconnect error is gone with version 1.2.2 and the notifications are now working as it should :)

omg, this is good news, thank you so much ❤️
let me know if you got other issue 🥰

**Comment by frankebobdk** [comment]
Hi, 

So everything is working fine except the countdown timer. It's still 2 minutes no matter what program we choose. 
If I install the previous version 1.5 it's showing the correct time. 

But even though the timer is 2 minutes behind I still get the notifications on time, which is weird. I don't have any disconnect errors or anything like that as before. Maybe there a bug in the way the countdown is "calculated"? I don't know 🤷🏼‍♂️

**Comment by nVuln** [comment]
> Hi,
> 
> So everything is working fine except the countdown timer. It's still 2 minutes no matter what program we choose.
> If I install the previous version 1.5 it's showing the correct time.
> 
> But even though the timer is 2 minutes behind I still get the notifications on time, which is weird. I don't have any disconnect errors or anything like that as before. Maybe there a bug in the way the countdown is "calculated"? I don't know 🤷🏼‍♂️

because LG count timer in minute, and Homekit count it in second, so I don't update remain duration too much, maybe this is reason, I'll try my best to handle it in future update

**Comment by frankebobdk** [comment]
awesome - and thanks for all work you put in this plugin, appreciate it 👍

**Comment by frankebobdk** [comment]
Just another quick note - when the washer sends the "Door is locked" notification through homekit it's exactly 2 minutes behind, but when the washer ends its program I get the notification on time.
