### ISSUE TITLE
"Mismatching Redirect URI Error" 

### ISSUE THREAD

**Issue by coneybeare** [nVuln/homebridge-lg-thinq#94]
**Describe The Bug:**

Trying to get redirect token, seeing "Mismatching Redirect URI Error" error.

**To Reproduce:**

```
 ruby 2.7.3p183@ ~  %  thinq auth -c US -l en-US
Log in here: https://us.m.lgaccount.com/spx/login/signIn?country=US&language=en-US&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&redirect_uri=https%3A%2F%2Fus.m.lgaccount.com%2Flogin%2FiabClose&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha&callback_url=https%3A%2F%2Fus.m.lgaccount.com%2Flogin%2FiabClose&oauth2State=12345&show_select_country=N
Then paste the URL where the browser is redirected:
```

![Screen Shot 2021-10-24 at 11 38 41 AM](https://user-images.githubusercontent.com/35369/138601492-41478cd3-788b-4805-ba00-02011f6f50f0.png)

**Expected behavior:**

I would expect the redirect to work

**Logs:**

```
N/A
```

**Plugin Config:**

```
N/A
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by nVuln** [comment]
> @nVuln does the second account have to use the same email address? I'm asking because I used sign in w/ Apple and hide my email.

no need to use same email as 2nd account, just create new account by any email you have, make sure it's LG account
